### ISSUE TITLE
command 'openapi.createNewThree' not found

### ISSUE THREAD

**Issue by julianlam** [42Crunch/vscode-openapi#1]
Hi!

Unfortunately, after installing the plugin, I receive this error when attempting to create a new OpenAPI v3 (or v2) file.

**What I did**

1. Install the plugin via Extensions sidebar (searched for `openapi` and selected your plugin)
1. Promptly crashed vscode because I hadn't restarted after vscode upgraded
1. Reinstalled the plugin via step 1
1. `ctrl-shift-p` `new open`, selected option to create new OpenAPI file

**What I saw**
![Screenshot from 2019-06-12 12-33-33](https://user-images.githubusercontent.com/923011/59369401-5b294280-8d0e-11e9-8990-a1053c2483e1.png)

**Comment by julianlam** [comment]
For tracking purposes, I found out about this project via https://openapi.tools/

**Comment by ak1394** [comment]
Thanks for you feedback and detailed instructions to reproduce @julianlam ! Indeed the extension would not activate until any .json file was opened first, and therefore commands to create new OpenAPI files where not available.

I've published the 1.6.6 update to address this issue. Please let me know if it works for you now.

**Comment by bjkeller** [comment]
Just FYI. I ran into this with a new project using VS Code 1.57.0 on Mac: Adding a new file wasn't working after enabling workplace trust. But ran successfully after restarting Code.

**Comment by ak1394** [comment]
Thanks for the info!

That workspace trust stuff is pretty new, so it's probably do to with the VS Code itself. With the next release of YAML extension which we depend on the issue should hopefully go away, as both extensions would support restricted mode https://github.com/redhat-developer/vscode-yaml/issues/500
