### ISSUE TITLE
Audit request fails when using yaml anchors

### ISSUE THREAD

**Issue by quezak** [42Crunch/vscode-openapi#100]
### Issue

In my `components/schemas` I'm sometimes using a YAML `&anchor` and its merge operator (`<<: *anchor`), notably in object property definitions, to avoid repetitions when one object type extends another. If such anchors are used, requesting the security audit fails:

1.If the anchor is used in a `$ref`erenced separate file, as pasted below, the error says: ![image](https://user-images.githubusercontent.com/666206/100109672-5b6abe80-2e6c-11eb-9438-8af230b9b3c9.png)
2. If I merge the files below instead of `$ref`erencing the other file, the error says: ![image](https://user-images.githubusercontent.com/666206/100109603-4beb7580-2e6c-11eb-8216-79f500b2fdaf.png)

The SwaggerUI preview rendering in the extension works fine, so does using the `openapi-generator` on such a spec.

If I delete the anchor, and just copy the first object's properties into the second object's properties, the extension works correctly.

### Minimal example

1. `test-api.yml`
```yaml
openapi: '3.0.3'

info:
  version: 0.0.1
  title: Test

paths:
  /foo:
    $ref: './paths-foo.yml#/paths/~1foo'

security:
  - ApiKeyAuth: []

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Api-Key
```

2. `paths-foo.yml`
```yaml
openapi: '3.0.3'

info:
  version: 0.0.1
  title: test paths -- see main file test-api.yml

paths:
  /foo:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTestObj'
      responses:
        '201':
          description: A created test object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestObj'

components:
  schemas:
    NewTestObj:
      type: object
      properties: &NewTestObjProperties
        name:
          type: string
        size:
          type: number
      required:
        - name
    
    TestObj:
      type: object
      properties:
        <<: *NewTestObjProperties
        id:
          type: string
          format: uuid
      required:
        - id
        - name
```

**Comment by quezak** [comment]
SwaggerUI renders correctly even when using the anchor:
![image](https://user-images.githubusercontent.com/666206/100110870-c072e400-2e6d-11eb-8684-60562f0ff0d8.png)

**Comment by ak1394** [comment]
Thanks for the detailed example, will take a look!

**Comment by ak1394** [comment]
This is fixed in the next release (should be published in a couple of days). 

I would personally advice against using YAML anchors as it adds additional level of complexity to OpenAPI. 

Using http://json-schema.org/understanding-json-schema/reference/combining.html (and taking https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#schema-object into consideration) is better, as it would not hide the source of schema definitions from the tools which validate JSON schemas and are not aware of YAML anchors.

**Comment by quezak** [comment]
@ak1394 thanks for the fix!

Yeah I know, so I'm using the anchors only in really obvious case where they don't impact schema readability and validation, like the one I posted.

Unfortunately the JSON-schema combinators don't work in this case, because (1) they're poorly supported in generators (or not at all in my case (typescript)), (2) they work a bit different -- even the docs say that [_`allOf` can not be used to “extend” a schema to add more detail_](http://json-schema.org/understanding-json-schema/reference/combining.html#allof), and they have some proposals for next versions.
