### ISSUE TITLE
External References

### ISSUE THREAD

**Issue by laltomar** [42Crunch/vscode-openapi#101]
It looks like external references are not supported, see below example.

$ref: "https://api.swaggerhub.com/domains/myapi/mydomain/1.0.0#/components/schemas/SelfLinkGet"

**Comment by ak1394** [comment]
Yes, the external references to non-local files (http/https) are currently not supported.

**Comment by ltshb** [comment]
Is there any plan for the external references support ?

**Comment by ak1394** [comment]
Yes, we're planning to add external refs support in the next version or one after that.

**Comment by ak1394** [comment]
Fixed in version 4.x
