### ISSUE TITLE
$ref URLs mangled

### ISSUE THREAD

**Issue by mcandre** [42Crunch/vscode-openapi#102]
The plugin insists on treating all `$ref` URLs as local files, forcibly URL-encoding the value and prepending `file:///`. This of course results in an invalid location, which then fails to open in the preview window.

**Comment by ak1394** [comment]
Could you provide an example? The extension currently does not support non-local refs though, perhaps we could fail with a better error message though.

**Comment by ak1394** [comment]
Just in case, we will be adding support for http/https refs to the plugin.

**Comment by donaldpipowitch** [comment]
> Just in case, we will be adding support for http/https refs to the plugin.

You mean something like this will work in the future:

```
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/restful-api-guidelines/problem-1.0.1.yaml#/Problem'
```

This currently prevents me from using previews. ❤️

![image](https://user-images.githubusercontent.com/1152805/105457216-bbbc8780-5c86-11eb-9d4c-783cc8fee02c.png)

**Comment by ak1394** [comment]
Yes, correct something like that should work!

**Comment by donaldpipowitch** [comment]
This is awesome news. Thank you😍

**Comment by ak1394** [comment]
Fixed in version 4.x
