### ISSUE TITLE
The preview button is not present in VSCode and no settings

### ISSUE THREAD

**Issue by carlevison** [42Crunch/vscode-openapi#103]
Not sure if this is an issue, or something I haven't set up correctly. I can't see the preview button in VSCode when I have a spec open, and in the extension settings I don't see the option to select a default preview renderer.

**Comment by ak1394** [comment]
Hi! When you have OpenAPI file open, do you see the entries in the OpenAPI ( API Icon) panel on the left? 

The option to select the default preview renderer should be in the Settings -> Extensions -> OpenAPI -> Default Preview Renderer do you see it there?

**Comment by carlevison** [comment]
Yes - I see the entries in the panel on the left. But, no, I don't see the Default Preview Renderer option. Only the Security Audit Token option.

**Comment by ak1394** [comment]
Could you check what version of the "OpenAPI (Swagger) Editor" extension you've got instaled?

**Comment by carlevison** [comment]
Sorted - thanks. I was on a very old version: 1.8.21 - that was the version that was installed automatically. I was also on an old version of VSCode, so after updating that, I was able to install version 3.9.0. Thanks for your help.
