### ISSUE TITLE
preview does not render a property referencing another property under #components/schemas

### ISSUE THREAD

**Issue by tigerinus** [42Crunch/vscode-openapi#105]
Say I have following schemas defined, where `#/components/schemas/ProductGroupRuleMultipleChoice/properties/rule_type` references `#/components/schemas/ProductGroup/properties/rule_type`:

```yaml
    ProductGroup:
      properties:
        group_uid:
          type: string
          example: 776e51fe-bb44-4888-a086-59c2476b3a02
        product_list:
          type: array
          items:
            $ref: "#/components/schemas/Product/properties/product_uid"
        rule_type:
          type: string
          enum:
            - MULTIPLE_CHOICE
        rule:
          discriminator:
            propertyName: rule_type
          oneOf:
            - $ref:  "#/components/schemas/ProductGroupRuleMultipleChoice"
    ProductGroupRuleMultipleChoice:
      properties:
        rule_type:
          $ref: "#/components/schemas/ProductGroup/properties/rule_type"
        max_choice_count:
          type: number
          minimum: 1
          example: 1
```

There is no lint error or warning. The yaml is perfectly syntaxed. However in the preview render, the `rule.rule_type` is missing:

![image](https://user-images.githubusercontent.com/7172560/105749297-3567a600-5f11-11eb-826b-8f73a1cc38b6.png)

**Comment by ak1394** [comment]
It looks like the issue is caused by a circular reference, the rule_type: $ref in ProductGroupRuleMultipleChoice points back to ProductGroup. It looks like SwaggerUI which this extension uses to render the preview has a problem with these.

I would avoid circular references if possible.

**Comment by tigerinus** [comment]
> It looks like the issue is caused by a circular reference, the rule_type: $ref in ProductGroupRuleMultipleChoice points back to ProductGroup. It looks like SwaggerUI which this extension uses to render the preview has a problem with these.
> 
> I would avoid circular references if possible.

Isn't it a fair statement to refer a subtype's discriminator property back to the discriminator specification at AnyOf level?

I could copy the type info to the subtype but that's a duplicate information which is less elegant IMO.

**Comment by ak1394** [comment]
Its the question of the tooling support, even if the spec allows it. I'd try to keep it simpler, even at cost of some duplication. BTW 42Crunch Security Audit doesn't allow circular references at all...

**Comment by ak1394** [comment]
Please re-open is this still an issue.
