### ISSUE TITLE
collapse (">") and expand ("v") don't work correctly

### ISSUE THREAD

**Issue by troofeds** [42Crunch/vscode-openapi#108]
When using collapse & expand on code in perfect openapi (yaml) file, the collapsing is in some places hiding also the first line of the next block at the same level, thus making it impossible to see what the next block is.

**Comment by ak1394** [comment]
Hi @troofeds ! We depend on [RedHat YAML](https://github.com/redhat-developer/vscode-yaml)  extension for YAML support. This is most likely an issue which needs to be raised there. I appreciate if you can open issue there, or if you provide some examples I can do it on your behalf.
