### ISSUE TITLE
Takes keybindings.json as OAS file

### ISSUE THREAD

**Issue by sguillia** [42Crunch/vscode-openapi#11]
When opening VS Code `keybindings.json`, the extension complains about:

> Incorrect type. Expected "object".

![Capture du 2019-08-21 19-08-05](https://user-images.githubusercontent.com/15984272/63452722-41f7ed00-c447-11e9-967a-bec5fe0049a4.png)

I have to disable the extension while editing my keybindings.

Thank you

**Comment by ak1394** [comment]
Thanks for reporting it! We'll address this issue in the next update.

**Comment by ak1394** [comment]
Fixed in 1.8.10
