### ISSUE TITLE
parameters and $ref not working

### ISSUE THREAD

**Issue by harshithjv** [42Crunch/vscode-openapi#111]
This is supported by OpenApi spec document: https://swagger.io/docs/specification/describing-parameters/#common-for-various-paths

But did not work for me. It just says `No parameters` on preview screen. Check all the file paths and link names. Just simply does not work and no error too.

**Comment by ak1394** [comment]
Could you share the sample? Also, this plugin supports two preview modes, one using SwaggeUI and another using ReDoc (although SwaggerUI is the default one). Could you try ReDoc preview? It is available through the command "OpenAPI: show preview using ReDoc"
