### ISSUE TITLE
SSL False positive problem after the last update

### ISSUE THREAD

**Issue by odelvalle** [42Crunch/vscode-openapi#112]
I have models hosted in local using nginx server and auto-firm certificate, and I have localhost as approved hostname.

Failed to resolve reference: Error reading file "\v2\content\article.yaml: cannot open openapi-external-https://localhost/models/v2/content/article.yaml. Detail: unable to verify the first certificate"

**Comment by ak1394** [comment]
Hi! It looks like VS Code is unable to verify your certificate, and refuses to open this file because of that.

Since you're using 'localhost' in your $refs, perhaps it's easiest to switch to use http:// instead of https://
