### ISSUE TITLE
Unexpected error when trying to audit API: URIError: URI malformed

### ISSUE THREAD

**Issue by DSotnikov** [42Crunch/vscode-openapi#114]
Looks like invalid $refs lead to the "Unexpected error when trying to audit API: URIError: URI malformed" error in Security Audit, but there is no indication of which $ref that is. See the screenshot. Would be good to add the corresponding issue to the Problems pane and to underline the $ref to indicate the error.
![image](https://user-images.githubusercontent.com/6956107/109574918-a288d100-7aa5-11eb-9d08-ab717717e534.png)

**Comment by ak1394** [comment]
Yep, this should not happen. Please share example of the invalid $ref

**Comment by DSotnikov** [comment]
Here you go: [petstore.zip](https://github.com/42Crunch/vscode-openapi/files/6065311/petstore.zip)

**Comment by ak1394** [comment]
I don't see any invalid URLs in the file attached. I did fix the issue where the "URI malformed" exception wasn't properly handled. Fix will go to the next release.

**Comment by DSotnikov** [comment]
I couldn't find any either, so this failure was very perplexing to me

**Comment by ak1394** [comment]
So, does it still happen when you try to audit petstore.yaml from this zip? I can audit it successfully.

**Comment by DSotnikov** [comment]
I cannot audit it. I am getting the error as shown on the screenshot.

**Comment by Favourkass** [comment]
i am having this error rn
