### ISSUE TITLE
Errors on latest version using externally references components

### ISSUE THREAD

**Issue by savage-alex** [42Crunch/vscode-openapi#115]
Since the latest version 4.1.0 we are seeing errors where a response is referenced from an external file:

VScode with plugin disabled
![image](https://user-images.githubusercontent.com/25430683/109943522-312b6700-7ccd-11eb-9eda-5fabb0c231ab.png)

VS code with plugin enabled
![image](https://user-images.githubusercontent.com/25430683/109943591-43a5a080-7ccd-11eb-9c67-cf963006d745.png)

To reproduce us the following YAML as a response on a path
responses:
        "204":
          description: Updated successfully
        "400":
          $ref: 'https://api.swaggerhub.com/domains/AdvancedComputerSoft/advanced-common-oas3/1.3.0#/components/responses/Problem400Response'

The shared domain is public so it should work.

or you are welcome to use the API def here: https://app.swaggerhub.com/apis/AdvancedComputerSoft/example-pet-inventory/1.0.5

**Comment by ak1394** [comment]
Thanks for the detailed report. The issue has been fixed and will be a part of the next release.

**Comment by savage-alex** [comment]
WOW thank you for the super fast response and fix!!! Great job

**Comment by ak1394** [comment]
Having the sample really helped, thanks! Fix has been released in 4.1.1

**Comment by savage-alex** [comment]
Thanks for the fix! all working great!!!
