### ISSUE TITLE
[Feature Request] OpenAPI root directory configuration

### ISSUE THREAD

**Issue by lachaib** [42Crunch/vscode-openapi#117]
Hello,

I'm opening this ticket because the OpenAPI documentation is not at the root of the repository that I'm mounting in the workspace, so I can't use this extension to display, navigate or edit the OpenAPI documentation (I could open the subfolder as another workspace folder or in another instance of VS Code but it's not convenient as I'm using Remote-Containers).

Would it be possible to add a configuration to specify the root to OpenAPI files?

Thanks

**Comment by ak1394** [comment]
Could you provide an example of your configuration? I.e. where the files are located, etc? I don't think the location of the root of repository should matter much for the extension. The only case where location would be relevant is in case where external $refs are used to build one OpenAPI file from multiple ones.

In any case a small example with file locations and relevant OpenAPI files would be helpful.

**Comment by lachaib** [comment]
Hello,

Repository is private and it would take me some time that I don't have today to replicate as a sample, but basically the tree looks like this:

.git/
src/
package.json
rest_api/v2/
|- index.yaml
|- components
|- paths
...

The only thing I can do with extension in this state is "Create new OpenAPI file" and is not able to attach the view to existing file in a subdirectory.
Note: I have tried to rename index.yml to index.yaml to comply with what I saw in the README of the extension but it changed nothing.

All references are internal to the repository.

I will try to create a sample case if need be but basically you could try to move any OpenAPI doc you have to a subfolder of your repo and you'd have the same behaviour.

**Comment by ak1394** [comment]
I don't see anything in particular in the structure of the repo that would be problematic. For one, if you open any OpenAPI file regardless of the location, you should see the components of the OpenAPI file shown in the outline  (see screenshots) it you see "No OpenAPI file selected" in there, it means that the extension did not recognize your file as OpenAPI file.

The extension checks json/yaml files for presence of "swagger: 2.0" attribute of "openapi: 3.0.x", does your index.yaml have these? 

<img width="281" alt="Screenshot 2021-03-05 at 14 53 38" src="https://user-images.githubusercontent.com/148276/110132699-5bf7e700-7dc3-11eb-9acf-2db99fe71088.png">

<img width="281" alt="Screenshot 2021-03-05 at 14 54 18" src="https://user-images.githubusercontent.com/148276/110132688-5a2e2380-7dc3-11eb-9be3-eda3e802959e.png">

**Comment by ak1394** [comment]
Please re-open is this still an issue.

**Comment by Stargateur** [comment]
sometime it's work sometime it's doesn't work, it's annoying to not be able to say "pin this file" and rely on a automatic detecting tool.

**Comment by ak1394** [comment]
Well, it should always work. I could definitely have a look if you can help with reproducing it.

The content of OpenAPI panel gets cleared if  you click away from the file, for example like here where the second column is selected (and petstore-v3.yaml is deselected). 

Could something like that be happening in your case?
<img width="1440" alt="Screenshot 2021-03-30 at 21 11 17" src="https://user-images.githubusercontent.com/148276/113050265-8b202f00-919c-11eb-95e1-d4d4af6137e8.png">

**Comment by Stargateur** [comment]
On my screenshot you can see the the file is selected cause color match and the top level of vscode show the the current active file is "openapi.yaml" ps: I'm not stupid. The bug is random so I can't retake a screen. I feel the bug is related to git somehow. If I have more detailed repro I will tell you.

**Comment by ak1394** [comment]
Thanks!

**Comment by rmangi** [comment]
I'm having the same problem with a yaml spec. A json version of it works though. I wonder if another plugin is conflicting?

**Comment by ak1394** [comment]
There's been changes in the new v4.4.0 release which are likely to address this issue. Please let me know if you still experience it.

**Comment by rmangi** [comment]
Still broken for me.

**Comment by ak1394** [comment]
I've introduced some bugs in the 4.4.0 which should be fixed in the version 4.4.1 release today.

Could you re-try and see if you still having the issue?

**Comment by rmangi** [comment]
Nope, still not working for a yaml file.
<img width="697" alt="Screen Shot 2021-04-13 at 12 29 30 PM" src="https://user-images.githubusercontent.com/1558468/114587975-2c56bd00-9c54-11eb-82c2-f02a4ae7fbac.png">

**Comment by ak1394** [comment]
@rmangi what versions of VS Code and RedHat YAML plugin do you have?

Looking at the screenshot, I don't see a schema title which normally appears at the top of the editor (ie. Validation schema for OpenAPI Specification...) as shown in the attached screenshot.

Also, you said you have problem with yaml but json works. Just to double check, has yaml ever worked? Does it sometime works, and some time doesn't or it has never worked?

<img width="835" alt="Screenshot 2021-04-13 at 17 38 27" src="https://user-images.githubusercontent.com/148276/114589533-abadb600-9c7f-11eb-9907-97e984296288.png">

**Comment by rmangi** [comment]
> @rmangi what versions of VS Code and RedHat YAML plugin do you have?

The latest I believe, 1.55.1 and  0.17.0 
> 
> Looking at the screenshot, I don't see a schema title which normally appears at the top of the editor (ie. Validation schema for OpenAPI Specification...) as shown in the attached screenshot.

No, I don't. I noticed that as well.

> 
> Also, you said you have problem with yaml but json works. Just to double check, has yaml ever worked? Does it sometime works, and some time doesn't or it has never worked?

It's never worked. The yaml validates fine offline and I use it to generate go code. It's valid as far as other tools are concerned :-)

**Comment by rmangi** [comment]
Oy! The problem was that it was `.yaml` and not `.yml`. That doesn't seem like it should make a difference.

**Comment by ak1394** [comment]
Ah, it's good that it never worked. The earlier fixes were for the cases where it would work, but then sometimes stop working, so that's clearly not your case. 

Could you see if you have something funny in Settings -> Text Editor -> Files -> Associations ? 

Maybe VS Code is configured to  associate .yaml files with some other language, and not with YAML?

If nothing of suspicion is there, maybe you can try to specifically associate *.yaml with 'YAML' language.
To do that, run 'Change Language Mode' from Command Palette (Shitf-CMD-P) then choose "Configure File Association for '.yaml'" and select YAML from the dropdown.

**Comment by rmangi** [comment]
Yes! That was it. I had yaml associated with something else from long ago! It's working. Thank you very much.

**Comment by ak1394** [comment]
You are very welcome! I'm happy we've figured it out!

**Comment by Stargateur** [comment]
@ak1394 I didn't have this problem the two last time I work on my openapi specification. And since I installed spectral it's way more easy to see error in the file.

**Comment by ak1394** [comment]
Thanks @Stargateur ! I hope the latest fixes resolved it, but please let me know if the issue reappears.
