### ISSUE TITLE
[Feature Request] Support Redoc-style external markdown in descriptions fields

### ISSUE THREAD

**Issue by austpaul** [42Crunch/vscode-openapi#119]
Support, or at least prevent failed preview rendering when using the Redoc convention of embedding external markdown

https://redoc.ly/docs/api-reference-docs/embedded-markdown/

**Comment by ak1394** [comment]
Hi! I understand why you'd want this, but the the use of $refs in descriptions is not permitted by OpenAPI specification. I think we're going to stick to spec here, and will not implement it.
