### ISSUE TITLE
YAML dependency update 5.0 breaks extension.

### ISSUE THREAD

**Issue by allstargg** [42Crunch/vscode-openapi#12]
Updating the YAML extension by Red Hat from 0.4.1 to 0.5.0 breaks the functionality of this extension.

**Comment by ak1394** [comment]
Thanks for reporting! I'm investigating the issue.

**Comment by ak1394** [comment]
Lack of validation and autocompletion when using 0.5.x version of Redhat Yaml extension is caused by a regression: https://github.com/redhat-developer/vscode-yaml/issues/216

Hopefully it should be resolved soon, but for the time being a workaround is to downgrade YAML extension to version 0.4.1

**Comment by ak1394** [comment]
RedHat has released new version 0.5.2 of YAML plugin which fixes this issue.
