### ISSUE TITLE
Examples in SwaggerUI Preview are hard to see when using light theme

### ISSUE THREAD

**Issue by baincd** [42Crunch/vscode-openapi#121]
In the SwaggerUI Preview, within example blocks the text color appears to come from (or is related to) the vscode theme, but the background color of the example block is always black regardless of the vscode theme.  When using a light theme, this color combination (dark-themed text colors and a black background) makes the text very difficult to read

With vscode Light theme (difficult to read the dark red and pink against the black background):
![image](https://user-images.githubusercontent.com/5075659/112729277-bf2bf380-8f01-11eb-80b3-832ea5489cf8.png)

Compared to with vscode Dark theme (example much easier to read):
![image](https://user-images.githubusercontent.com/5075659/112729302-d8cd3b00-8f01-11eb-9b75-066d5e024c81.png)

**Comment by ak1394** [comment]
Thanks for reporting the issue! Some vs code default styles were affecting the preview. It should be fixed in the next release.
