### ISSUE TITLE
[REQ] New tab with all operation objects

### ISSUE THREAD

**Issue by ybelenko** [42Crunch/vscode-openapi#122]
There is `PATHS` section in current version(4.3.0) of plugin UI, but most of time I cannot recall specific API path while I remember `operationId`.

It might be very useful to have `OPERATIONS` section with list of all declared operations(`operationId` prop as link label). I find this type of navigation more convenient than using `PATHS` tab.

**Comment by ak1394** [comment]
Thanks for suggestion! I'll update the ticket later on how we decide to proceed with that.

**Comment by ak1394** [comment]
We've implemented Operations ID panel in the new v4.4.0 release
