### ISSUE TITLE
Reference path auto completion

### ISSUE THREAD

**Issue by klementtan** [42Crunch/vscode-openapi#124]
It would be great if the is some sort auto-completion when typing the value of `$ref`

**Comment by klementtan** [comment]
If this feature requests is accepted, I would like to contribute and try to implement it 😄

**Comment by ak1394** [comment]
Hi @klementtan thanks for the offer! We have some $ref completion implemented here: https://github.com/42Crunch/vscode-openapi/blob/master/src/completion.ts if you want to improve it, you're more than welcome!

**Comment by klementtan** [comment]
@ak1394 Thanks for getting back to me. Add a small fix that allows for `$ref` completion in `yaml` files with single quotes #126

**Comment by ak1394** [comment]
Thanks a lot for your contribution @klementtan ! I've merged your changes, and it'll make to the next release of the extension. If you can think of any other improvements you're more than welcome!
