### ISSUE TITLE
the editing assistant has stopped working for me

### ISSUE THREAD

**Issue by rcrooks** [42Crunch/vscode-openapi#131]
sadly this very handy VSC extension for openapi docs has stopped working for me - only provides shortcuts to the operationIDs now, not the paths or components. 
<img width="355" alt="2021-06-08_10-59-38" src="https://user-images.githubusercontent.com/619617/121210172-740b5680-c849-11eb-9da2-3af1d8d4b114.png">

Any ideas on how to get it working again? 

Ps. I see the same behavior in the general release and the Insiders Build.

**Comment by ak1394** [comment]
Hi! Thanks for reporting the issue. Perhaps something's up with the structure of the document? Can you share your OpenAPI file? 

Alternatively, try creating a new OpenAPI file by pressing Cmd-Shift-P and selecting "OpenAPI: Create new OpenAPI v3.0 file (YAML)". It should create a file with "/test" path in it which should be visible in the panel.

**Comment by rcrooks** [comment]
ah, uninstalling and reinstalling the extension fixed it 🥇

**Comment by rcrooks** [comment]
H @ak1394 re-opening this. So, uninstalling and reinstalling the extension does fix the problem, but only temporarily. It soon returns to this state of showing only operation ids, but nothing else. It's not an issue with the openapi files, as they validate (I have a couple of dozen of them, and see the same behavior on all.

Same behavior if I run OpenAPI: Create new OpenAPI v3.0 file

**Comment by ak1394** [comment]
Hi @rcrooks !

Could you restart VS Code, open one of the OpenAPI files and the go Help -> Toggle Developer Tools and  look at the "Console" tab of developer tools panel?

Is there any error messages? Perhaps you could maximize it and take a screenshot of it?

**Comment by rcrooks** [comment]
HI @ak1394 - well, while I was working on getting you a screenshot of console errors, I noticed some others unrelated to this, and uninstalled the problem extensions. Then restarted VS Code, and voila, all is well. Not sure which of the other extensions was causing the problem...
Thanks for getting back to me though!

**Comment by rcrooks** [comment]
closing again

**Comment by ak1394** [comment]
@rcrooks no problem at all! I'm pretty interested to know if any particular extension conflicts with our extension, so if you run into any more issues, please let me know!

**Comment by rcrooks** [comment]
@ak1394 will do!
