### ISSUE TITLE
Incorrect Problems shown when file extension is "yaml"

### ISSUE THREAD

**Issue by soumyakantiroychowdhury** [42Crunch/vscode-openapi#14]
Version 1.8.10
VS Code version: 1.37.1

OpenAPI 3.0 files, if extension is "yaml", it shows warnings / problems like "Property openapi is not allowed" etc. As soon as file extension is changed to "yml", these warnings go away.
![image](https://user-images.githubusercontent.com/14230950/63745084-e7371900-c8be-11e9-9db1-eb0380bc535f.png)
![image](https://user-images.githubusercontent.com/14230950/63745111-fb7b1600-c8be-11e9-80c9-d985f7a6751b.png)

**Comment by ak1394** [comment]
I can't reproduce this issue. Could you possibly share a swagger file which causes it to manifest? Are you on windows/linux/mac? What version of YAML plugin do you have installed?

**Comment by soumyakantiroychowdhury** [comment]
An yaml as simple this:

```
openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
```

I am on Windows 10. Version of YAML plugin by Red Hat is 0.5.1.

**Comment by ak1394** [comment]
Could you try downgrading YAML plugin to version 0.4.1, there is currently an issue with versions 0.5.x: https://github.com/42Crunch/vscode-openapi/issues/12

**Comment by soumyakantiroychowdhury** [comment]
Looks like _downgrading YAML plugin to 0.4.1_ is **the** solution. Thank you very much for your help, @ak1394 - much appreciated.

**Comment by DSotnikov** [comment]
RedHat has released new version 0.5.2 of YAML plugin which fixes this issue.

**Comment by soumyakantiroychowdhury** [comment]
> RedHat has released new version 0.5.2 of YAML plugin which fixes this issue.

Yes, I tried that - but that has introduced a new warning (around the schema reference in $ref) - so I again reverted to 0.4.1 and happy with that!

**Comment by ak1394** [comment]
What's the warning you're seeing with 0.5.2? We'd like to fix it if possible.

**Comment by ak1394** [comment]
I've found the issue with the $ref and YAML 0.5.2 and published a new version of our extension which includes workaround for this problem. You should be able to update to YAML 0.5.2 if you wish so.
