### ISSUE TITLE
Errors in validation & audit with $ref files in parameters and responses properties

### ISSUE THREAD

**Issue by mikelax** [42Crunch/vscode-openapi#141]
# Issue

We have an Open API spec document that is broken down into multiple files to make working with a larger API easier to manage. With multiple files, the Open API spec in total is valid and works correctly. 

I have noticed though that the VS Code plugin reports an error for the following two sections under components:
* parameters
* responses

Errors reports:
>According to the OpenAPI Specification, property 'parameters' must be of type 'parameter object', found type 'string'
>According to the OpenAPI Specification, property 'responses' must be of type 'response object', found type 'string'

Everything else works fine, even other sections under components like schemas, for example.

## Reproduction Steps

[This open api file](https://github.com/dgarcia360/openapi-boilerplate/blob/master/src/openapi.yaml) contains an example that is valid, but produces the error in question. 

Clone this repo: `git@github.com:dgarcia360/openapi-boilerplate.git`
Open the file `src/openapi.yaml` file in VS Code.
Perform security audit, observe the above errors.

Ensure spec file is valid:
```bash
npx @apidevtools/swagger-cli validate  src/openapi.yaml
```
Result:  `src/openapi.yaml is valid`

**Comment by ak1394** [comment]
Hi! There might be some issues around how we process multi-file OpenAPIs, but let's take it one step at a time.

Looking at openapi.yaml I see this:

```
components:
  parameters:
    $ref: "./parameters/_index.yaml"
```

Which is invalid according to OpenAPI specification https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#components-object

It says that "parameters" is Map[string, Parameter Object | Reference Object] but what you have in there is a "Reference Object" contained directly in the "parameters".

**Comment by mikelax** [comment]
Hi @ak1394 I appreciate the help. I understand your point about the reference object, but what is odd is that only these two components cause a problem. For example, the `schemas` component has the same Type defined in the spec, but the plugin works correctly , so there is not consistency between how the different components are handled. 

Based on what you said I would expect all components to cause problems, or them all to work. 
Also, I have tried two different linter / validator packages on this example spec and it passes for both, so I think the `$ref` should be accepted here.

**Comment by ak1394** [comment]
Well, the reason why "schemas" work, is an artifact of this particular file structure and the way handling of multi-file OpenAPIs is implemented in this extension. At the moment we use somewhat lax approach of handling external $refs which results in extension supporting files which are not valid according to the OpenAPI spec.

In the future versions, I expect that we will handle it more carefully, and start rejecting or showing errors for all non-valid files.

I know if looks convenient to structure your API definition in this manner, but unfortunately what you get in the result is not a valid OpenAPI file, and it becomes a matter of chance if some particular tool supports this standard deviation or not.
