### ISSUE TITLE
Unexpected error when trying to audit API: HTTPError: Response code 400 (Bad Request)

### ISSUE THREAD

**Issue by Favourkass** [42Crunch/vscode-openapi#142]
idk what the issue is
![Screenshot 2021-09-15 at 21 48 11](https://user-images.githubusercontent.com/81357407/133507254-bc3e197e-94b3-4d9a-a6e8-c5b29fe94a56.png)

**Comment by ak1394** [comment]
Can you share the OpenAPI file that you're trying to audit?

**Comment by Favourkass** [comment]
okay  here is the link

**Comment by Favourkass** [comment]
https://drive.google.com/file/d/1P6Kqcvy-ECWr-BS--vVCzGQgQDngzPU4/view?usp=sharing

**Comment by Favourkass** [comment]
i uploaded the file to my google drive and made it accessible

**Comment by ak1394** [comment]
Hi! Thanks for uploading the file! The audit fails because the file is too big. Currently the maximum allowed file size is 2Mb.
The error message is not helpful though, I'll make it more descriptive.
