### ISSUE TITLE
Add debounce to rendering of Preview window

### ISSUE THREAD

**Issue by shadoath** [42Crunch/vscode-openapi#145]
### Issue: 
The UI rerenders on every change in the YML. This causes a flash in the display window.  

### Solution:
Adding a debounce to this event.
 - The settings can have an option to change the default values
   - Milliseconds past last change
   
Thank you for consideration of this issue. I think it would be a great addition to the extension.

**Comment by ak1394** [comment]
Hi @shadoath ! Thanks a lot f for a suggestion. Are you talking about the flashing in the "preview" window?

**Comment by shadoath** [comment]
Yup, that's exactly what I'm dealing with. 
Right now I hide it behind another tab cause it is too distracting when I'm editing a file.

**Comment by ak1394** [comment]
Added "Preview Update Delay" in the recent release.
