### ISSUE TITLE
Add option to disable auto refresh of preview

### ISSUE THREAD

**Issue by wtjones** [42Crunch/vscode-openapi#146]
The preview window constantly tries to update as I type. This drags down the performance of the editor as it tries to render invalid state.

Plantuml also has this issue, but can be solved by disabling auto update and assigning a shortcut to refresh the preview. A setting similar to the following would be a welcome addition.

```
"plantuml.previewAutoUpdate": false
```

**Comment by ak1394** [comment]
This seems to be a similar issue to https://github.com/42Crunch/vscode-openapi/issues/145 we'll address it in the next release of the extension.

**Comment by ak1394** [comment]
The new release introduced "Preview Update Delay" setting. If you'd like to disable preview, set it to something large and use preview keyboard shortcut (Shift-Option-P) to trigger the preview.
