### ISSUE TITLE
How to edit preview options

### ISSUE THREAD

**Issue by crystalfp** [42Crunch/vscode-openapi#148]
Thanks for this extension! Really useful.
I need to edit the `curl` command provided in the SwaggerUI preview for "Try it out". Is it possible? I need to add the `-k` option because my development server is using a self signed certificate.
Thanks for considering!
mario

**Comment by ak1394** [comment]
Unfortunately It's not possible to configure SwaggerUI in the current version of the extension. However there is a configuration mechanism that SwaggerUI exposes which can be used, and we'll see if we can expose it in the future versions.

**Comment by crystalfp** [comment]
OK, thanks. I'll wait for a future version.

**Comment by Martwall** [comment]
> Thanks for this extension! Really useful. I need to edit the `curl` command provided in the SwaggerUI preview for "Try it out". Is it possible? I need to add the `-k` option because my development server is using a self signed certificate. Thanks for considering! mario

What you can do until a future version with options are released is use [mkcert](https://github.com/FiloSottile/mkcert) to generate the certificates for your development server.
