### ISSUE TITLE
Intellisense not working for .yaml files

### ISSUE THREAD

**Issue by chandanch** [42Crunch/vscode-openapi#15]
Intellisense does not work for swagger.yaml file. Even the hot key(ctrl + space) does not give any intellisense.

![image](https://user-images.githubusercontent.com/8663552/63841751-01492800-c9a1-11e9-8c78-8eb0b8328773.png)

**Comment by ak1394** [comment]
It's a know issue unfortunately: https://github.com/42Crunch/vscode-openapi/issues/12 there is work ongoing in RedHat extension and we expect a fix soon.

**Comment by ak1394** [comment]
Oh, and the workaround is to downgrade YAML extension to 0.4.1

**Comment by DSotnikov** [comment]
@chandanch Red Hat has released new version 0.5.2 of YAML plugin which fixes this issue.
