### ISSUE TITLE
Use Intellisense Individually In JSON/YML Files

### ISSUE THREAD

**Issue by msudgh** [42Crunch/vscode-openapi#150]
My socket documentations are stored in the following directory structure in the form of OpenAPI for payloads, events, and responses, but there is one thing missing from this idea, and I was wondering would extension support intellisense individually within JSON/YML files without defining openapi file structure?

**Tree:**

<img width="399" alt="Screen Shot 2021-12-06 at 16 10 43" src="https://user-images.githubusercontent.com/11756815/144847717-0b172531-ab14-4ca6-a905-09be2ef8803e.png">

**Sample File:**

<img width="807" alt="Screen Shot 2021-12-06 at 16 15 30" src="https://user-images.githubusercontent.com/11756815/144848343-aa08b3ff-71db-4b3a-bd80-ff709ac7bf6c.png">

**Comment by ak1394** [comment]
Hi @msudgh! Unfortunately intellisence will not work in a project structured like that,  we rely on the OpenAPI schema for intellisence (we don't implement most of it, instead it "just works" if the JSON schema is provided), and the files shown above do not match OpenAPI schema.
