### ISSUE TITLE
Editor Preview won't open: Failed to generate preview, check OpenAPI file for errors.

### ISSUE THREAD

**Issue by ANTGOMEZ** [42Crunch/vscode-openapi#151]
Using OpenAPI editor, latest with VsCode
Version: 1.63.0 (user setup)
Commit: 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
Date: 2021-12-07T06:26:56.179Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

It used to work for me, but now it doesn't, no OS or VSCode changes. Issues above error when I Invoke the editor preview window: **Failed to generate preview, check OpenAPI file for errors.**

How can I see what the actual error is?

My OpenAPI file is formatted correctly, has no errors.

I uninstalled and re-installed the extension, still same issue.

Ideas?

Thanks!

**Comment by ak1394** [comment]
Hi! One of the resent changes in the extension which might be related to your issue is that we started to threat the duplicate keys in JSON as an error, but in this case you should see an error highlighted in the body of your file.

Could you share your OpenAPI file so I could have a look at it?

**Comment by ANTGOMEZ** [comment]
Here's the file:

swagger: '2.0'
info:
  description: 'This is the swagger page for Data Catalog API. You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/)'
  version: 1.0.0
  title: Data Catalog API
  termsOfService: http://swagger.io/terms/
  contact:
    email: eibi@ebs.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: datacatalog-api.ebiqa.com
basePath: /
tags:
  - name: bulk
    description: Bulk (file) downloading from and uploading to Data Catalog
paths:
  /bulk/download:
    get:
      tags:
        - bulk
      summary: Performs a bulk filtered download of Articles and Titles
      description: Download Articles. <br>Filters are <b>case-sensitive</b>. <br>Keep all 3 filter fields empty to get all articles. <br>Enter an <b>Existing</b> Email (your own email in most cases)
      operationId: bulkDownload
      parameters:
        - name: templateName
          type: string
          in: query
          description: Filter by Template Name
          required: false
        - name: articleName
          type: string
          in: query
          description: Filter by Article Name
          required: false
        - name: parentName
          type: string
          in: query
          description: Filter by Parent Name
          required: false
        - name: userEmail
          type: string
          in: query
          description: Email
          required: true
          pattern: '^[a-zA-Z0-9._-]+@[eE][bB][sS]\.[cC][oO][mM]$'
      responses:
        '202':
          description: Download request was accepted, please check email with the link to download the file
        '400':
          description: 	Error occurred in download request
        '502':
          description: Internal Server Error. Please, try again later
        '504':
          description: Server Error. Please, try again later
  /bulk/upload:
    post:
      tags:
        - bulk
      summary: Performs a bulk upload of Articles given file input from user
      description: Upload Articles. <br>Enter an <b>Existing</b> Email (your own email in most cases)
      operationId: bulkUpload
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: file
          type: file
          in: formData
          description: Select the Catalog file to upload
          required: true
          format: file
        - name: userEmail
          type: string
          in: query
          description: Email
          required: true
          pattern: '^[a-zA-Z0-9._-]+@[eE][bB][sS]\.[cC][oO][mM]$'
      responses:
        '202':
          description: Upload file has been accepted, upload details will be sent via email
        '400':
          description: Error occurred during file upload
        '502':
          description: Internal Server Error. Please, try again later
        '504':
          description: Server Error. Please, try again later
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io

**Comment by ANTGOMEZ** [comment]
sorry about the formatting here, github changes it. But in actuality it's correct, no errors.

**Comment by ak1394** [comment]
Thanks for providing the sample (it's easier to just drag-n-drop a file into the comment box) but this way it worked as well.

There seems to be an issue in both the file and our extension :). The problem with the file is that there is a Tab character on line 51 (the line reads "description: Error occurred in download request") if you replace it with the space it will solve the issue.

The problem with the extension, that we did not show the relevant error in the text editor, I'll address it in the one of the next releases.

**Comment by ANTGOMEZ** [comment]
Yup, that was it. Thanks!! I'll turn on Show All Chars in vscode. Woulda caught that.

**Comment by ak1394** [comment]
Latest release shows tabs present in the YAML file as errors
