### ISSUE TITLE
Using keyword `const` throws error: "Property const is not allowed"

### ISSUE THREAD

**Issue by aryzing** [42Crunch/vscode-openapi#153]
When using `const`, there's an error reported regarding it's use.

This is the code I'm trying to create,

```yaml
components:
    schemas: 
        AdminUser:
            allOf:
            - $ref: "#/components/schemas/User"
            - type: object
                properties:
                foo:
                    const: bar
```

The error is `Property const is not allowed.`.

**Comment by ak1394** [comment]
There is no `const` in schemas supported by OpenAPI 3.0.x (assuming you're using this version) and 3.0.x is the latest version currently supported by this extension.

Details: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.1.md#schemaObject
