### ISSUE TITLE
Creating a new yml file open a new tab for each characters

### ISSUE THREAD

**Issue by tchandelle** [42Crunch/vscode-openapi#154]
### Steps to Reproduce:

1. Create a new unsaved file
2. Select YAML as language mode
3. Type *anything*
4. A new tab is created for each character

When disabling this extension, the issue does not occur.

### Versions

42crunch.vscode-openapi v4.6.4

Vscode
Version: 1.63.1
Commit: fe719cd3e5825bf14e14182fddeb88ee8daf044f
Date: 2021-12-14T02:02:02.183Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.0-91-generic

Also tested on same version on OS: Darwin x64 20.6.0

**Comment by ak1394** [comment]
Thanks for reporting! I can't reproduce the issue on Mac, will try on Linux later.

**Comment by ak1394** [comment]
Yes, reproduced here as well!

**Comment by ak1394** [comment]
The issue is fixed in the upcoming release, which should be published in the next few days.

**Comment by tchandelle** [comment]
I tested on master, i confirm it's fixed. Thanks.
