### ISSUE TITLE
Error on startup/Swagger UI Preview for schema with external URL

### ISSUE THREAD

**Issue by GravlLift** [42Crunch/vscode-openapi#156]
When starting VS Code with the extensions installed, I get the following exception in my `Log (Window)` output:

```
[2021-12-29 10:31:00.283] [renderer1] [error] Unexpected exception while bundling: TypeError: Cannot read property 'indirections' of null: Error: Unexpected exception while bundling: TypeError: Cannot read property 'indirections' of null
    at c:\Users\Jason\.vscode\extensions\42crunch.vscode-openapi-4.7.1\out\bundler.js:224:23
    at Generator.throw (<anonymous>)
    at rejected (c:\Users\Jason\.vscode\extensions\42crunch.vscode-openapi-4.7.1\out\bundler.js:25:65)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at listOnTimeout (internal/timers.js:523:9)
    at processTimers (internal/timers.js:497:7)
```

Attempting to use the `OpenAPI: show preview using Swagger UI` also triggers the same exception with a slightly different call stack (same end line, different starting line). I would assume that attempting to take any extension action would also trigger this. The preview tab does not appear, and there is no feedback outside of the log window.

Extension Version: v4.7.1 (also tested in v4.6.4, with the same result)
VS Code Version Information:
```
Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
```

**Comment by GravlLift** [comment]
The issue seems to be specific to swagger documents with external URL references, as I can get the preview working by removing them.

It seems like perhaps the extension should be prompting to approve the host of the external URLs, but is instead failing silently.

**Comment by ak1394** [comment]
Thanks for reporting, could you share your OpenAPI file?

**Comment by GravlLift** [comment]
Here's a minimal reproduction:

```
openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Minimal repro'
paths:
  /user:
    get:
      tags:
        - User
      description: Get current user information
      responses:
        '200':
          description: 'User information found'
        default:
          $ref: '#/components/responses/error'
components:
  responses:
    error:
      description: Unexpected error
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/problem'
  schemas:
    problem:
      $ref: 'https://zalando.github.io/problem/schema.yaml#/Problem'
```

**Comment by ak1394** [comment]
Thanks for providing the sample, this issue will be fixed in the upcoming release of the extension which is expected in the next couple of days.
