### ISSUE TITLE
Can't use openapi extension when yaml/ansible extensions also installed

### ISSUE THREAD

**Issue by MVKozlov** [42Crunch/vscode-openapi#159]
I can't use openapi extension when yaml/ansible extensions also installed

I think will be much better if extension register own openapi.json/openapi,.yaml language
so it can be selected in 'Change Language Mode' or in file associations

**Comment by MVKozlov** [comment]
Update: seems It can be solved with
```# yaml-language-server: $schema="http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json"```
in the beginnging of `file.openapi.yaml`
and
``` json
"files.associations": {
   "*.openapi.yaml": "yaml"
}
```
in `settings.json`

**Comment by ak1394** [comment]
Hi @MVKozlov ! Do you by any chance seeing the same issue as https://github.com/42Crunch/vscode-openapi/issues/130 ? Otherwise could you specify what do you mean by "can't use openapi extension"?

Regarding your proposed fix, unfortunately this will require our users to change their OpenAPI file contents or filenames, which is something we can't impose on them.

**Comment by MVKozlov** [comment]
@ak1394, Without `#comment schema` line **ansible** extension always takes precedence over **vscode-openapi**. When I try to create new openapi spec all working as intendent, but right after `saving` it get switched back to **ansible**.
If I manually switch language to `YAML`, it just plain yaml without openapi schema

And about my solution. It's just a workaround for anyone interested, so I propose a  to make openapi a first class language.

**Comment by ak1394** [comment]
Thanks for your suggestion! I would've liked to make OpenAPI a language as well, but unfortunately VS Code APIs for contributing a language are not flexible enough.

A language definition in VS Code relies on combination of the following:  file name extensions, file name patterns, files that begin with a specific line (see https://code.visualstudio.com/api/references/contribution-points#contributes.languages for details).

Unfortunately it's not enough to rely on these to tell if particular JSON or YAML file is OpenAPI or not.
