### ISSUE TITLE
Unable to install on VSCode zip extractor

### ISSUE THREAD

**Issue by pradeepjaladi** [42Crunch/vscode-openapi#16]
Unable to install the plugin in VSCode on version 1.30.1 on zip extract.

Version: 1.30.1
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:12:07.165Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.16299

**Comment by ak1394** [comment]
This plugin has started to use some newer VS Code APIs and now requires modern version of VS Code. Could you try upgrading to 1.37.1 ?
