### ISSUE TITLE
"Property definitions is not allowed." error

### ISSUE THREAD

**Issue by clement-estone** [42Crunch/vscode-openapi#164]
Hi there 👋 

I've just started to use this extension to design some APIs and so far it's been really great, it works amazingly well and has saved me quite a lot of time.

But I've encountered a little bug while using it: in YAML files, the `definitions` field is not suggested when using autocompletion, and when specifying it I get the following error `Property definitions is not allowed.`

This happens for both JSON and YAML files, and it also disables autocompletion and structural validation for types that are written inside. But, if I open the Swagger preview pane, they are correctly handled and integrated in the API calls where I used them.

Could this be a configuration problem on my side? I didn't find anything while looking for this issue, so if you know how to solve this issue, please let me know :)

**Comment by ak1394** [comment]
Hi @clement-estone ! Can you send an example of your OpenAPI file?

**Comment by ak1394** [comment]
Thanks for providing the sample, it makes it clear what the issue is, the "definitions" is OpenAPI 2.0 (swagger) the 3.x versions of OpenAPI have "components" instead. Have a look here: 

https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md
