### ISSUE TITLE
Enhancement to support external references to JSON schema files

### ISSUE THREAD

**Issue by kevben79** [42Crunch/vscode-openapi#168]
We would like to reference external JSON schema files defining components from within the main open api spec document.  Currently I know external files have to conform to Open API 3 spec format.  We already have a bunch of standard JSON schema files for our common API components like person, address etc. and we want to reference and use these and have the local rendering in Swagger.  Support for this feature would be the icing on the cake for us, meaning we do not have to duplicate everything we have already (the existing component part schema files are used for in code validation).

**Comment by ak1394** [comment]
I guess the full support for this will come once 3.1 is implemented. As it stands, strictly speaking 3.0.x swagger can't use "pure" JSON Schema, and uses variation of JSON Schema "adjusted" to the OAS standard.
However, the minute differences between the two might not exists in your use case, and it could be that extension does support at least a subset of your use-case.

Can you share an example of your OpenAPI files/schemas?

**Comment by kevben79** [comment]
Thanks for coming back to me... when building a simple example to share, I can see it working.  Therefore closing this issue, apologies for wasting time.

**Comment by ak1394** [comment]
No worries at all! Happy to see all kinds of feedback.
