### ISSUE TITLE
Request and Response Not Rendering application/xml

### ISSUE THREAD

**Issue by attunedlabs** [42Crunch/vscode-openapi#169]
# Problem

When trying to preview an OAS file where `requestBody` or `responses` contains only *application/xml* or starts with *application/xml*, the schema syntax will not render. When copying the same file into the swagger editor, it renders properly.

Simply replacing "application/xml" with "application/json" will cause JSON to render properly, however, XML is desired.

## System Configuration

**OAS Version**: 3.0.2

**Plugin Version**: 4.9.3

**IDE Configuration**:
Version: 1.66.0 (user setup)
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:14.623Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19042

# Example
<img width="595" alt="image" src="https://user-images.githubusercontent.com/50338746/161848933-43500021-93fd-4d64-8fb3-a9e55625d919.png">

```json
{
    "openapi":"3.0.2",
    "info": {
      "title":"Rendering Fail",
      "version":"1.0",
      "description": "Sample for demonstrating XML issue",
      "contact": {
        "name": "API Owner",
        "url": "https://google.com"
      }
    },
    "servers": [
      {
          "description": "Example Server",
          "url": "demo.application/v1"
      }],
    "paths": {
        "/sendit": {
            "post": {
                "summary": "Does a POST",
                "operationId": "posting",
                "requestBody": {
                    "required": true,
                    "description": "my custom post",
                    "content":{
                        "application/xml": {
                            "schema": {
                                "$ref": "#/components/schemas/body"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                      "description": "successful operation",
                      "content": {
                        "application/xml": {
                          "schema": {
                            "$ref": "#/components/schemas/body"
                          }
                        }
                      }
                    }
                  },
                  "x-codegen-request-body-name": "body"
            }
        }
    },
    "components": {
        "schemas": {
            "body": {
                "type": "object",
                "properties": {
                    "action": {
                        "type": "string",
                        "example": "mydata"
                    }
                },
                "xml": {
                    "name": "body"
                }
            }
        }
    }
  }
```
# Expected Result (via swagger editor)
<img width="917" alt="image" src="https://user-images.githubusercontent.com/50338746/161849867-fd685f49-57db-44e0-908f-28a3fe64a303.png">

**Comment by ak1394** [comment]
Thanks for your feedback and providing a sample. I have reproduced the issue and will let you know once we have a fix.

**Comment by ak1394** [comment]
The issue has been fixed, and fix will be a part of the next release of the extension.
