### ISSUE TITLE
Low performance on big OpenAPI spec file (yaml)

### ISSUE THREAD

**Issue by ipotseluev** [42Crunch/vscode-openapi#178]
I have 13K lines OpenAPI file (yaml) and the extension makes editor very laggy (big response time from keyboard actions). When I disable the extension, I can't see the issue.

OS: MacOS 12.4

**Comment by ak1394** [comment]
Hi @ipotseluev ! Thanks for the feedback. Can you share your OpenAPI file? I've tried to repeat the issue with 30k YAML file, and I don't experience lag with it. CPU usage increases, as it re-parses spec every second or so to update outlines, etc. but doesn't cause a much of a lag (I've tried it on MacBook pro). Alternatively, if you're willing to try it, I can produce a build for you with decreased parsing frequency so we can check if that makes a difference.

**Comment by ipotseluev** [comment]
Hi @ak1394 . Unfortunately I can't provide the spec, because it's proprietary. But I can test your build if it might be helpful to the extension. I'm also using Mac book pro, Intel 2019

**Comment by ak1394** [comment]
Hi @ipotseluev ! Please try the attached package (I had to zip it to attach it, so please unzip and install using "Install from VSIX..." menu option in Extensions).

Let me know if you see the performance improvements. If the issue persists, try increasing the "Delay between document updates" in Settings / Extensions / OpenAPI (you'll need to restart VS Code after changing this setting).

[vscode-openapi.zip](https://github.com/42Crunch/vscode-openapi/files/9316618/vscode-openapi.zip)

**Comment by ipotseluev** [comment]
@ak1394 I've tried your version out and compared it with the standard version several times. Your version doesn't have any notable performance issues while editing text (that's the most notable case with the problem). It's much-much better.

**Comment by ak1394** [comment]
Thanks a lot for reporting the issue in a first place. Looks like I broke
some performance optimisations and it did go unnoticed for a while. I’ll
publish the changes as a part of normal release as soon as it clears QA.

**Comment by ak1394** [comment]
Fixed in 4.13.0
