### ISSUE TITLE
required string fails if empty

### ISSUE THREAD

**Issue by Desencuentro** [42Crunch/vscode-openapi#182]
## The problem
Trying to execute an operation with an empty required string fails validation.
The following snippet was used:

```
"schema": {
    "type": "object",
        "properties": {
            "Username": {
                "type": "string",
                "example": "admin"
            },
            "Password": {
                "type": "string",
                "example": ""
            }
        },
    "required": [ "Username","Password" ]
}
```

### Expected behaviour
According to OpenAPI, the `required` keyword is taken from [JSON Schema](http://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.6.5.3):

> The following properties are taken directly from the JSON Schema definition and follow the same specifications:
> …
> required

And it means (section 6.5.3 of JSON schema):

> An object instance is valid against this keyword if every item in the [required] array **is the name of a property in the instance**.

So, an empty string should it's supposed to be valid (as it also complies with string type), and the operation should be executed.

### Observed behaviour
The field is shown in red ans tilts, as expecting to insert something, instead of executing the operation.

![image](https://user-images.githubusercontent.com/73045355/184248317-7f2007e0-3e3a-4ce7-af32-7737089cbf15.png)

**Comment by ak1394** [comment]
Hi! Thanks for the feedback, and sorry for a late response. The issue however is seems to be related to SwaggerUI which we use to render the OpenAPI preview https://github.com/swagger-api/swagger-ui it would be best to report it there.
