### ISSUE TITLE
Persistant Audit problems

### ISSUE THREAD

**Issue by DigiLive** [42Crunch/vscode-openapi#188]
First of all, I'm not sure to post the issue at this repo, but this is where the generated Audit Report sent me for giving feedback.
I'm defining an OpenAPI spec, using PhpStorm 2022.2.2 and version 1.41 of this [plugin](https://plugins.jetbrains.com/plugin/14837-openapi-swagger-editor).
(Perhaps another bug?)

---
When I perform an audit, all problems get listed in an _Audit Problems_ tool window.
Some problems remain listed after performing an audit again.
- Some fixed problems remain listed while they're already solved.
- Some unfixed problems get a duplicate listing.

The report itself behaves like expected.
Restart (and invalidating caches) of PhpStorm doesn't change this behavior.

**Comment by ak1394** [comment]
I'll close this issue, so let's continue with the new one. If you're unable to share OAS file, please provide before and after screenshots at https://github.com/42Crunch/intellij-openapi-editor/issues/25
