### ISSUE TITLE
Your AST CLI is broken

### ISSUE THREAD

**Issue by yangsec888** [42Crunch/vscode-openapi#193]
Type: <b>Bug</b>

Got the error code 403 - "Unable to list collections, please check your 42Crunch credentials: getaddrinfo ENOTFOUND platform.us.42crunch.com" when sync with platform. I'm a platform.us.42crunch.cloud user with legit token. 

Extension version: 4.15.9
VS Code version: Code 1.73.1 (Universal) (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:08:38.961Z)
OS version: Darwin x64 19.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (2.79GB free)|
|Process Argv|. --crash-reporter-id 9faee68e-4b88-45bc-ba0d-b84f42f00b06|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30595537
3biah626:30602489
gswce2:30605431
iaj6b796:30608729
dbltrim-noruby:30604474
89544117:30607850

```

</details>

**Comment by ak1394** [comment]
Hi @yangsec888 !

It looks like the platform URL is incorrectly set. It tries to contact "platform.us.42crunch.com" host while the correct host name is "platform.us.42crunch.cloud".

Could you please run "42Crunch: Update platform credentials" from the command palette (Ctrl-Shift-P on windows or Cmd-Shift-P on mac) and update platform URL to "https://platform.us.42crunch.cloud/"

**Comment by yangsec888** [comment]
Good catch. Please close this ticket for me.

**Comment by ak1394** [comment]
Happy to help! Closed.
