### ISSUE TITLE
Does this tool support swagger 2.0 to openapi 3.0 converstion

### ISSUE THREAD

**Issue by rkrepala** [42Crunch/vscode-openapi#195]
Hi, I'm looking for a tool to convert swagger 2.0 to Open API 3.0 conversion. Let me know does this tool supports or not? Thanks

**Comment by ak1394** [comment]
No, this extension does not support it. Try https://editor.swagger.io/ instead (load swagger file and try Edit -> Conver to OpenAPI 3 in the menu)
