### ISSUE TITLE
yaml support would be awesome ;)

### ISSUE THREAD

**Issue by nullp0int3r** [42Crunch/vscode-openapi#2]

**Comment by ak1394** [comment]
Yes, indeed! This is the next planned feature for the extension.

**Comment by nullp0int3r** [comment]
good news, thank you ;)

**Comment by victorsebrito** [comment]
looking forward to this!

**Comment by ak1394** [comment]
We've just published an update with basic YAML support - mainly navigation, commands for modifying YAML files are not yet implemented. We're going to bring YAML support to feature parity with JSON in the next release. In the meantime please try it out, your feedback is welcome!

**Comment by foobarto** [comment]
it's picking up other yaml files as openapi/swagger yaml files for some reason too. 

I have a `.gitlab-ci.yml` file in same repository as `swagger.yml` and it's showing an error `Unable to load schema from: 'openapi:file:///<path>/.gitlab-ci.yml' Error: Request: custom/schema/content failed with message: Cannot read property 'document' of undefined`

**Comment by ak1394** [comment]
Thanks for reporting this @foobarto I'll investigate!

**Comment by ak1394** [comment]
I've published 1.8.3 version of the extension, which adds commands for modifying YAML files and fixes issue reported by  @foobarto 

As of this version YAML support in the extension should be on the same level as JSON support.

**Comment by psaxton** [comment]
When this extension is enabled, other files such as cloud formation template.yaml files report errors for tags defined in the yaml.customTags setting. This does not happen with other extensions using the js-yaml engine such as redhat.vscode-yaml, ms-azuretools.vscode-docker, and ms-kubernetes-tools.vscode-kubernetes-tools.

I can report this as a separate issue if necessary.

**Comment by psaxton** [comment]
I just realized this issue is closed. I will create a separate issue.
