### ISSUE TITLE
in paths show parameters and returns in a sub-tree

### ISSUE THREAD

**Issue by JasonHenriksen** [42Crunch/vscode-openapi#20]
I'm really loving the use of this tool, but as I'm trying to make sure that things are correct, it would be helpful to see the parameters and responses under the verbs in the path area.

I can't find source code, but I'd be happy to submit a PR to add that feature if you're interested.   Otherwise, I hope you'll consider the feature request.

Thank you!

**Comment by ak1394** [comment]
Thanks for feedback! My main concern is that adding additional nodes under operations might make path panel more cluttered. However I will certainly look at it, perhaps I'm wrong.

I appreciate the offer to do a PR, however we're still sorting out some internal issues before we can publish source code. I hope to release it soon.

**Comment by ak1394** [comment]
Now displaying parameters and responses in version 2.0.1.
