### ISSUE TITLE
Embedding .md in description gets flagged as incorrect type

### ISSUE THREAD

**Issue by jeanjackson-lp** [42Crunch/vscode-openapi#200]
When I embed a Markdown file as `$ref` in the `description:` property under `info:` and `tags:`, I get the following message under **PROBLEMS**:

`Incorrect type. Expected "string".`

This is valid, though, and renders with no issue on our site:

```openapi: '3.0.0'
info:
  version: 1.0.0
  title: My example API
  description:
    $ref: /path/to/file.md
```

**Comment by ak1394** [comment]
According to OpenAPI specification: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md you can't use refs in these locations. If you look at the spec you'll notice that is specifies particular locations where 'Reference Object' can be used, and 'description' field is no one of them.
