### ISSUE TITLE
Receiving error while running yaml on OPEN API extension

### ISSUE THREAD

**Issue by ankitasingh170190** [42Crunch/vscode-openapi#201]
Getting this error when running the api endpoint via open api plugin in VS Code. The API is hosted on AWS API Gateway

The same works fine on a postman. 

I verified the curl command from both platforms and they match.

This is the error I receive

   
Failed to fetch.
Possible Reasons:

CORS
Network Failure
URL scheme must be "http" or "https" for CORS request

**Comment by isamauny** [comment]
Hello, are you a 42Crunch customer using our platform ? If yes,  please open a ticket on support.42crunch.com so that we can help you.
