### ISSUE TITLE
"Value is not accepted" error inside of PUT's "parameters > in" declaration

### ISSUE THREAD

**Issue by busybox11** [42Crunch/vscode-openapi#205]
I just installed this extension and i am getting errors on my API schema definition.
It appears that the extensions reports the use of `body` inside a PUT request parameter as invalid, and apparently only accepts the value `path`.

![Screenshot from 2023-02-13 15-23-50](https://user-images.githubusercontent.com/29630035/218484576-b9c8f923-c47e-4b15-91d4-f39719ab502c.png)

This does not appear to occur with `get` requests definitions, as I have some above with the same parameters and do not have the issue here.

**Comment by ak1394** [comment]
Could you please check that you don't have "type" property on your parameter, but instead use "schema"? Feel free to post the entire openapi file if you still have issue with it.

**Comment by busybox11** [comment]
Ah, I do have the `type` property. I probably got confused with the documentation.
I'm trying this rn, I'll keep you updated whenever I get something working.
Thanks for the fast reply btw!

**Comment by busybox11** [comment]
It does seem to work now. Thank you for the quick help!
And thanks for the amazing extension, it's already very useful to me haha
