### ISSUE TITLE
Support for splitted files definitions

### ISSUE THREAD

**Issue by blackyale** [42Crunch/vscode-openapi#21]
I think (please correct me if I am wrong) that it would be useful to support definitions that are splitted across multiple files since Openapi 3 allows it by using $ref: <filePath>.

I have been trying to work this way but I can't use features like 'Go to definition', etc...

Thanks in advance.

**Comment by ak1394** [comment]
Could you provide an example where it doesn't work? Also see https://github.com/42Crunch/vscode-openapi/issues/13

**Comment by ak1394** [comment]
I've fixed some issues in how we handle JSON Pointers which affect the "Go to definition" implementation. I expect that your issues should be resolved in the upcoming 1.8.18 update.

If this still doesn't work for you, please re-open and provide examples.
