### ISSUE TITLE
Audit requires a pattern even when a format has been defined

### ISSUE THREAD

**Issue by fednot-icc** [42Crunch/vscode-openapi#220]
When defining a format such as "date" or "email", the audit still complains that no pattern has been defined.

**Comment by dt42c** [comment]
Hi,
Please send the question to 42Crunch support team on the following URL:
https://support.42crunch.com/hc/en-us/requests/new
Thanks!

**Comment by fednot-icc** [comment]
#1038

**Comment by dt42c** [comment]
Ticket #1038 closed
