### ISSUE TITLE
self signed certificate in certificate chain

### ISSUE THREAD

**Issue by adurthisridhar** [42Crunch/vscode-openapi#225]
Hi Team,

While I am integrating 42Crunch in VS Code, facing below error. Does any one have resolution for this? I have followed all the steps mentioned in VS Code and 42Crunch integration. Provided the 42Crunch platform URL and IDE token as well. But same error is keep on coming. Not sure how to resolve this. No clue at all. Your help is really approciated.

Failed to connect
RequestError: self signed certificate in certificate chain

**Comment by adurthisridhar** [comment]
I was able to resolve this issue by myself by using below properties in settings.json

"http.proxyStrictSSL": false,
"http.proxy": "<< here you need to use your company's proxy URL",
"http.proxyAuthorization": null

**Comment by ak1394** [comment]
Hi @adurthisridhar ! Cheers for fixing it yourself, and sorry for a late reply... It was a busy end of the week, and your issue fell through the cracks, my apologies.
