### ISSUE TITLE
Doesn't recognize openapi yaml files (`No OpenAPI file selected`)

### ISSUE THREAD

**Issue by janvda** [42Crunch/vscode-openapi#229]
When opening an openapi yaml file it doesn't recognize is as an open API file.
When clicking on the yaml extension it says : `No OpenAPI file selected`
When clicking on `New OpenAPI file` button nothing happens.

FYI this is the start of that file:

```
openapi: "3.0.2"
info:
  title: Financial Declaration API
  description: |
    **This API manages the resource entity `Financial Declaration`**
```

FYI my version of visual studio code :

```
Version: 1.65.1 (Universal)
Commit: 8908a9ca0f221f36507231afb39d2d8d1e182702
Date: 2022-03-08T02:20:11.670Z (1 yr ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 22.4.0
```

**Comment by ak1394** [comment]
What is a filename of your openapi file? It could be related to this issue #184

**Comment by janvda** [comment]
I have upgraded to recent visual studio code version and now I no longer have this issue.

My new version of visual studio code =

```
Version: 1.79.1 (Universal)
Commit: 4cb974a7aed77a74c7813bdccd99ee0d04901215
Date: 2023-06-12T16:16:49.215Z (3 days ago)
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.4.0
```
