### ISSUE TITLE
Try-it: Parameter "in: path" for GET not passed

### ISSUE THREAD

**Issue by startailcoon** [42Crunch/vscode-openapi#233]
I'm ussing the try-it feature for this plugin, but it seems to not working, or I'm missing something.

I'm making a API with Slim Framework.

My OpenAPI yml file states the following
```
  /gettransaction:
    get:
      summary: Returns a specific transaction matching the given transaction id.
      parameters:
        - name: txid
          in: path
          description: The transaction id
          required: true
          schema:
            type: string
            example: c93aa81dbdede0477f1aa8876029d1094642841361eaad0a1de02d8a8fe0376f
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
```

My code to handle this request are
```
$app->get('/gettransaction/{txid}', function (ServerRequestInterface $request, ResponseInterface $response, array $args) {
 ... code here ....
}
```

When I try this out the following is filled out, which looks good to me
![image](https://github.com/42Crunch/vscode-openapi/assets/12114550/bf567d72-30c2-41f7-9dac-33227133ba68)

However, the request path does not contain the txid, it only requests `/v1/gettransaction`, not `/v1/gettransaction/c93aa....`.

Manually going to the correct Path works, it's just that the Try-it feature does not add it to the request.

I've tried to look through the documentation of Slim Framework and OpenAPI to see if I've missed something, but I'm turning up with nothing.

I use v4.18.2 of the Plugin for VSCode v 1.79.2.

**Comment by ak1394** [comment]
Hi @startailcoon ! It looks like your path is missing `txid` parameter. In your OpenAPI file Instead of ` /gettransaction:` it should be ` /gettransaction/{txid}:`

Think of it like this, you are saying that there should be a parameter called `txid`, but you don't say _where_ in the path should it be located.
