### ISSUE TITLE
yaml alias using `<<:` gives validation error

### ISSUE THREAD

**Issue by VazMike** [42Crunch/vscode-openapi#24]

**Comment by VazMike** [comment]
```openapi: 3.0.0
info:
  title: t
  description: d
  version: 0.0.1
x-limit: &limit
  type: integer
  format: int32
  minimum: 0
  maximum: 200
components:
  schemas:
    Obj:
      type: object
      properties:
        totalCount:
          <<: *limit
paths: {}
```

![image](https://user-images.githubusercontent.com/14861435/66577362-e82bbd80-eb81-11e9-8494-f198c3617bd4.png)

**Comment by ak1394** [comment]
We use https://github.com/redhat-developer/vscode-yaml for YAML editing support, autocompletion and schema validation. Unfortunately, it looks like the schema validation as implemented in vscode-yaml doesn't support `<<:` 

I need to investigate it further to see what can be done to address it, but it will likely take some time.

**Comment by ak1394** [comment]
Works in VS Code 1.46.1
