### ISSUE TITLE
How can I omit or ignore a certain audit issue?

### ISSUE THREAD

**Issue by chrislentz** [42Crunch/vscode-openapi#240]
I am building multiple OpenAPI specs, one is an internal use-only API.

With this spec, I would like to ignore certain audit rules. I checked to see if there was a way to do it in settings but didn't see anything. According to the documentation, these types of customizations to the audit tool can be added to the UI tool, but I can't find any documentation on how to add them to the extensions.

For instance, I would like to turn off "v3-schema-request-string-pattern".

**Comment by ak1394** [comment]
Hi @chrislentz !

You can use these extensions to customize how Audit works: https://docs.42crunch.com/latest/content/extras/x42c_extensions.htm

In particular you'd want to use `x-42c-skipIssues` to ignore selected issues.

**Comment by chrislentz** [comment]
Thanks @ak1394. Calling them extensions had me confused. I was looking for a VS Code extension. I got it added to my spec.json and it is working great.
