### ISSUE TITLE
Intellisense suggests !And !Base64 !Cidr etc. before properties, making it a bit more cumbersome to autocomplete

### ISSUE THREAD

**Issue by revosw** [42Crunch/vscode-openapi#247]
Personally, I never use the !And !Base64 !Cidr etc. properties (Not sure what they are called). This means I have to scroll down to get the properties I want. It would be nice to put the !And !Base64 !Cidr etc. properties at the bottom of the list
![image](https://github.com/42Crunch/vscode-openapi/assets/19785016/fd39f9c2-9a25-42f4-9aab-5aae84f05a62)

**Comment by ak1394** [comment]
Hi @revosw ! I don't think these items are added by our extension, most likely it's coming from other extension that offers autocompletion for YAML files. For instance `!FindInMap` looks like something from Amazon AWS?

There is an 'explain mode' in the completions widget which can help to find source of a particular suggestion: first open completions box (ctrl-space) then press cmd-? (on windows probably ctrl-?), it should look like this:
<img width="1078" alt="Screenshot 2023-11-14 at 00 09 04" src="https://github.com/42Crunch/vscode-openapi/assets/148276/6eb17d7d-80de-4972-8c1c-2d62b1592c2b">

**Comment by revosw** [comment]
Oh, I'm sorry, you're totally right!
