### ISSUE TITLE
Parameter fields in the Swagger Preview are not editable

### ISSUE THREAD

**Issue by svenax** [42Crunch/vscode-openapi#27]
When the preview in VSCode is initially rendered, the parameter fields are editable but as soon as I switch to another view to, for instance, copy some text, the fields become read only. Maybe this is a problem with the VSCode web view implementation, everything does of course work when opening the preview in a we browser.

**Comment by ak1394** [comment]
Hi! This extension does not have preview functionality. Perhaps you've submitted issue to a wrong project by mistake?
