### ISSUE TITLE
Doesn't install properly on closed network?

### ISSUE THREAD

**Issue by FractalK** [42Crunch/vscode-openapi#28]
Hello. 

Really excited to try this extension, but I am building in an offline environment. I downloaded the extension and loaded it into VS Code without any overt signs of issues. However, the extension's openAPI button does not load in the left-hand panel and upon trying to access any of the functionality, I receive errors like the following: 

_command 'openapi.createNewThreeYaml' not found_

I suspect there is some internet dependency that I don't appreciate, but I thought I would raise it in case this was an easy fix.
Thanks in advance.

**Comment by ak1394** [comment]
This extension depends on RedHat YAML extension: https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml 

I guess if you install this one as well it should work fine in offline install.

**Comment by FractalK** [comment]
Thanks! I will give it a try
