### ISSUE TITLE
Preview examples background varies across different themes

### ISSUE THREAD

**Issue by Hadi-Mohseni** [42Crunch/vscode-openapi#295]
Hello,

I'm new to this amazing extension, and I wanted to know if there's a way to change the background color of examples located in the preview panel. I've noticed that when you change the color theme in VSCode, it affects the appearance of the preview panel and its colors. To the point, when I select the **Default Dark High Contrast** theme, the background of examples ends up looking like the picture below, and it's difficult to read:

![openapi example background](https://github.com/user-attachments/assets/1920db18-fd5e-4645-8036-2b070b7eadcf)

which is not the case for other themes like **Visual Studio Light**:

![openapi example correct background](https://github.com/user-attachments/assets/0e8ea279-014d-416c-9223-d2f0ac4f33b1)

I've tried several approaches to find the settings related to the background color, but unfortunately, I couldn't locate the correct ones. I would greatly appreciate it if you could share the solution to this problem or the correct settings. Thank you.

**Comment by ak1394** [comment]
It looks like some of the VS Code styles affect the Swagger UI rendering. I'll have a look, thanks for reporting.

**Comment by ak1394** [comment]
This will be fixed by the next release, which is due to be published in a few days.

**Comment by Hadi-Mohseni** [comment]
@ak1394 

Thanks for keeping me updated on this! I won't reopen unless the issue persists after the next release. 
Looking forward to seeing it fixed then.

**Comment by ak1394** [comment]
The version with the fix has been published (4.30.0). If by any chance the fix didn't work, please re-open the issue.

**Comment by Hadi-Mohseni** [comment]
It has indeed been resolved. Thanks
