### ISSUE TITLE
Parameters are not recognize

### ISSUE THREAD

**Issue by LasneF** [42Crunch/vscode-openapi#3]
using this tiny swagger 
`{
    "swagger":"2.0",
    "info": {
        "title":"API Title",
        "version":"1.0"
    },
    "host": "",
    "basePath": "/",
    "schemes": ["https"],
    "paths": {
        "/test": {
            "get": {
                "description":"",
                "parameters": [  {
                    "name" : "tag",
                    "in" : "query",
                    "description" : "If at least one tag parameter is present, only apiVersions having at least one tag matching one of the queried tag will be returned",
                    "required" : false,
                    "type" : "array",
                    "items" : {
                      "type" : "string"
                    },
                    "collectionFormat" : "multi"
                  }, {
                    "name" : "category",
                    "in" : "query",
                    "description" : "If at least one category parameter is present, only apiVersions having at least one category matching one of the queried category will be returned",
                    "required" : false,
                    "type" : "array",
                    "items" : {
                      "type" : "string"
                    },
                    "collectionFormat" : "multi"
                  }, {
                    "name" : "subCategory",
                    "in" : "query",
                    "description" : "If at least one subCategory parameter is present, only apiVersions having at least one subCategory matching one of the queried subCategory will be returned",
                    "required" : false,
                    "type" : "array",
                    "items" : {
                      "type" : "string"
                    },
                    "collectionFormat" : "multi"
                  } ],
                "responses": {
                    "200": {
                        "description":"Success"
                    }
                }
            }
        }
    }
}`

the parameters are not recognized  (only path and operation is working

**Comment by ak1394** [comment]
Thanks for the feedback! The parameters shown in the outline are a globally defined parameters, i.e. contents of the "parameters" property defined on the same level as, for example, the "paths" property.

We don't currently show contents of individual operation objects in the outline. Maybe we should do it, I'll discuss it with my team.

**Comment by DSotnikov** [comment]
Hi, @LasneF,

As @ak1394 mentioned, we currently only putting the global parameters to the left-hand navigation bar.

For specific Paths, we put to Navigation the Paths themselves and the Verbs within them, but stop at that level. We think that in most cases, people would want to quickly navigate to the paths and verbs and then see the details within the OpenAPI file itself.

Is there a specific usecase for which you see the need for additional elements in the left-hand API navigation pane that are not there right now?
