### ISSUE TITLE
GNU License - Source Code Access Request

### ISSUE THREAD

**Issue by MagicSystem32** [42Crunch/vscode-openapi#30]
Hello,

I would like to know if it could be possible to get access to the code source of this extension which seems like the best right now in term of fonctionnalities for Visual Studio Code.

I didn't see any way to contact you (even or your website) if it wasn't for a demo, so I am writing this issue.

I am asking this because the other big Swagger's extension for VS code (https://github.com/arjun-g/vs-swagger-viewer) didn't have any update since 6 months (with a bit of "TODO" remaining in their README.md) because only 1 person was keeping it alive.
So, I would like to know more about the possibility to keep this one alive before using it too much. If we know the number of people working on it and if the **code is open source can be a decision-making factor**, being sure it will remains free and usable in any company I would be working in :) (even though VS code itself is an MIT license and "This agreement only gives you some rights to use the software. Microsoft reserves all other rights").

I am writing this issue because the extension is registered under a GNU license on the Visual Studio Code Marketplace (source: https://marketplace.visualstudio.com/items/42Crunch.vscode-openapi/license) while the only repository registered is this one, with the documentation, so I am asking if it could be possible **to access the code of this extension** per the terms of your license:
**"that you receive source code or can get it if you want it, that you can change the software or use pieces of it in new free programs, and that you know you can do these things"**

Thank you for reading and for considering my request.

Sorry for doing this in a public issue if it is just a problem of license taken for the referencing on VScode Marketplace, but getting in touch with you privately is too difficult.

Have a nice day!

**Comment by RandomFractals** [comment]
I second that. Such a great OpenAPI extension. Would be interesting to look under the hood & hopefully it's maintained by the original authors || contributors using it.

**Comment by RandomFractals** [comment]
@MagicSystem32 I pinged them on Twitter too since I shared it there just recently for devs to check out: https://twitter.com/TarasNovak/status/1191311159980376064

**Comment by MagicSystem32** [comment]
@RandomFractals Thank you for supporting this request 😉 

(And sorry that I cannot give more visibilities to your Tweet, I don't have Twitter anymore ☹️ )

**Comment by ak1394** [comment]
Source code has been published.
