### ISSUE TITLE
$ref flagged as error when (apparently) valid

### ISSUE THREAD

**Issue by nwpappas** [42Crunch/vscode-openapi#31]
I have several `$ref`s that are being flagged as in error in my schema:

![Screen Shot 2019-11-08 at 9 03 20 AM](https://user-images.githubusercontent.com/2529208/68496258-bbada480-0206-11ea-8313-b65ee553c873.png)

But, based on my understanding from the Array's documentation (https://swagger.io/docs/specification/data-models/data-types/#array) this should be valid. Additionally, if I copy/paste my complete schema into https://editor.swagger.io/ I get no errors.

**Comment by ak1394** [comment]
Yes, it should be valid to use $ref in arrays. Could you provide the entire OpenAPI file?

**Comment by nwpappas** [comment]
He's a smaller version of my OpenAPI file, which still exhibits the error in VS Code but not in the online Swagger editor.

```yaml
openapi: 3.0.2

info:
  title: Example $ref Error
  description: Optional description in CommonMark.
  version: 1.0.0-alpha.1

paths:
  /:
    get:
      summary: Returns the configuration.
      responses:
        200:    # status code
          description: A JSON object of the current configuration.
          content:
            application/json:
              schema:
                type: object
                properties:
                  services:
                    type: array
                    items:
                      $ref: '#/components/schemas/service'

components:
  schemas:
    service:
      properties:
        id:
          type: string
          format: uuid
        egress:
          type: object
          properties:
            pool:
              $ref: '#/components/schemas/pool'

    pool:
      properties:
        id:
          type: string
          format: uuid
```

**Comment by ak1394** [comment]
Hmm... I don't see any errors in VS Code in this example. What is the text of the error you're getting? It should show up in the 'Problems' section at the bottom of the screen.

**Comment by nwpappas** [comment]
![Screen Shot 2019-11-08 at 1 42 57 PM](https://user-images.githubusercontent.com/2529208/68512596-b57eee80-022d-11ea-8576-bcc095eab3f8.png)

I am currently working on a Mac; VS Code v 1.40.0.

**Comment by ak1394** [comment]
What's the version numbers of the OpenAPI and YAML extensions you're using? Is there any other openapi/swagger related extensions installed on your system? 

Your issue seems to be same as  https://github.com/42Crunch/vscode-openapi/issues/17 where the schema validator had issues dealing with relative URIs. I've added a workaround for it some time ago.

**Comment by nwpappas** [comment]
I had installed the extension this morning, having just found it. While trying to debug I did restart VS Code, but when I hit the Extensions browser to see the version there was a button to reload everything. I hit it. Everything seems fine now.

**Comment by ak1394** [comment]
It's a bit unusual, there was no changes to the extension for a couple of weeks, so nothing would've changed during the day. In any case, I'm glad it worked for you!
