### ISSUE TITLE
Feature Request: Definition never used warning

### ISSUE THREAD

**Issue by nwpappas** [42Crunch/vscode-openapi#32]
A nice addition to the linter would be to flag definitions that are defined, but never used. I've found this feature in the swagger.io editor useful on a few instances.

![Screen Shot 2019-11-08 at 9 17 11 AM](https://user-images.githubusercontent.com/2529208/68497142-bea99480-0208-11ea-89de-9842f8f30db5.png)

**Comment by ak1394** [comment]
Try running Audit, it warns on the unused schemas: https://github.com/42Crunch/vscode-openapi#use-the-extension-to-audit-security-of-your-api
