### ISSUE TITLE
$ref is not resolved when path contains "~1" (escaped slash)

### ISSUE THREAD

**Issue by kroleg** [42Crunch/vscode-openapi#34]
As per openapi specs https://swagger.io/docs/specification/using-ref/#escape `$ref`s can contain `~1`.
Latest version of extension doesn't support "go to definition" if path contains `~1`.
Here is an example repository with perfectly valid spec (redoc compiles it) and "go to definition" in vscode doesn't work there (in api.yml file): https://github.com/kroleg/openapi-ref-bug

P.S. I would like to make a PR if/when source code will become public

**Comment by ak1394** [comment]
Thanks for reporting the issue and especially providing a repo with the example of the problem. This issue has been fixed and will appear in the next release, which I expect to publish in a day or two.

As well, thanks for offering to do a PR! We're on track to release the sources before the end of the month.

**Comment by kroleg** [comment]
@ak1394 i just realized that problem with path resolving was because of `{` and `}` and not because of `~1`. I hope you figured it out already, so i am writing this just in case.

**Comment by ak1394** [comment]
Yes, indeed. The issue was related to a regex which tried to take into account a flow style definitions which contain curly braces too. Thanks for taking care to write this though!
