### ISSUE TITLE
Typo in "Schema allows additional properties" warning

### ISSUE THREAD

**Issue by bartocc** [42Crunch/vscode-openapi#35]
I've found a typo in the `Schema allows additional properties` warning:

```
Remediation
Clearly define the properties of both accepted inpust and outputs in your API.
```

See the `inpust` above?

Is there a repo where I could create a simple PR for this?

**Comment by ak1394** [comment]
Thanks for finding the typo! We'll fix it internally for now, but we expect to opensource code very soon, so further fixes would be made here.
