### ISSUE TITLE
Feature Request: copy the component path

### ISSUE THREAD

**Issue by FhyTan** [42Crunch/vscode-openapi#37]
Edit component path is a tedious work
Hope to add a function to copy the path of a component in the explorer pane, or autocomplete when I use the $ref.
Thanks for the nice extension.

**Comment by ak1394** [comment]
Thanks for submitting the request! We've plans to add autocompletion for $ref's, but copying paths from explorer seems like a nice idea as well!

**Comment by FhyTan** [comment]
> Thanks for submitting the request! We've plans to add autocompletion for $ref's, but copying paths from explorer seems like a nice idea as well!

Thank you very much!

**Comment by vfateev** [comment]
Fixed
