### ISSUE TITLE
Remove category "Language Packs" from extension package.json

### ISSUE THREAD

**Issue by gregvanl** [42Crunch/vscode-openapi#38]
The category "Language Packs" is for localized display languages such as German and Japanese. Please use the category "Programming Languages" for extensions that provide programming language features.

![image](https://user-images.githubusercontent.com/12818376/71531179-5ee37780-28a2-11ea-9b06-594946061317.png)

**Comment by ak1394** [comment]
Thanks for reporting! Fixed in the upcoming release.
