### ISSUE TITLE
Security key not working

### ISSUE THREAD

**Issue by kfb1007** [42Crunch/vscode-openapi#40]
I've tried to uninstall the extension so I will get prompt for email, but still get error on authentication.

**Comment by ak1394** [comment]
VS Code will not remove key on uninstall of the plugin. Could you try going to Settings -> Extensions -> OpenAPI and removing "Security Audit Token" value instead?

Once you remove it, try running audit again, you should see a prompt for an email and you should get a new key.

**Comment by kfb1007** [comment]
Thanks you!  That worked.
