### ISSUE TITLE
Bug: Problems loading reference 'openapi-schemas:openapi-2.0.json'

### ISSUE THREAD

**Issue by hilleer** [42Crunch/vscode-openapi#46]
When installing the extension and opening an OAS file, I get this error:

>Problems loading reference 'openapi-schemas:openapi-2.0.json': Unable to load schema from 'openapi-schemas:openapi-2.0.json': Request vscode/content failed with message: cannot open openapi-schemas:openapi-2.0.json. Detail: resource is not available.(768)

<img width="1050" alt="Screenshot 2020-03-17 at 14 27 34" src="https://user-images.githubusercontent.com/9430821/76860526-79067380-685b-11ea-96e6-9199ecb827d4.png">

**Comment by ak1394** [comment]
Thanks for reporting the issue! Does it happen with a particular file or all OpenAPI files you tried? In particular does it happen to .json or .yaml files? What's your platform and version of VS Code editor?

**Comment by hilleer** [comment]
Hi @ak1394 ,

Thanks for your response and sorry for not including any of that info at first.

* It is a `.json` file, I haven't tried to reproduce with YAML. Can do?
* Vscode version `1.43.0`.
* Latest version of the extension `2.1.1`.

**Comment by hilleer** [comment]
I tried to reproduce in a new file. I did not see the error until I deleted my original OAS file, then it appeared in the new file. When I restored the deleted file, I did not see the error in that file anymore  but only in the "new" file...

**Comment by ak1394** [comment]
I believe I've fixed the issue, although I could not reproduce it myself. Fix will be available in the next version, please re-open it it still happens to you.

**Comment by hilleer** [comment]
Great. Thanks a lot for looking into it @ak1394 .
