### ISSUE TITLE
Multiple examples for a parameter is not supported

### ISSUE THREAD

**Issue by bsergik** [42Crunch/vscode-openapi#47]

**Comment by ak1394** [comment]
It would be helpful if you provide a little more information, for example a sample file, so I have to guess here. The validation of OpenAPI files in the extension is done using officially provided schemas, so perhaps it's an error on your part?

Please see this blog post, in particular the "example vs examples" part https://apisyouwonthate.com/blog/openapi-v31-and-json-schema-2019-09

Feel free to reopen the issue if it's something else.
