### ISSUE TITLE
"null" type in schema should be included

### ISSUE THREAD

**Issue by yogsoft** [42Crunch/vscode-openapi#5]
**Sample Schema**:
```
"myField": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ]
          }

```
**Expected**: No validation error should be displayed

**Actual**: Below message displayed for "null" type

`Value is not accepted. Valid values: "array", "boolean", "integer", "number", "object", "string".`

**Comment by ak1394** [comment]
The OpenAPI specification (v3) https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#dataTypes says:

    ... null is not supported as a type (see nullable for an alternative solution).

so it looks like you should be using nullable instead.
