### ISSUE TITLE
Token is cut in some email client

### ISSUE THREAD

**Issue by simonech** [42Crunch/vscode-openapi#50]
Dears,
in my email client, Airmail 4, the token is not wrapped to a new line so, impossible to copy&paste it

![image](https://user-images.githubusercontent.com/61557/78577268-20107680-782e-11ea-9cb8-e0003fedf1d9.png)

I tried a few times and then went on Gmail where it was properly in multiple lines and possible to copy.

**Comment by ak1394** [comment]
Thanks for reporting! We'll look to update the email template we use to address the issue.

**Comment by DSotnikov** [comment]
@simonech 

I have doublechecked, and the email html actually does have `word-wrap: break-word;` set for that paragraph. Looks like Airmail 4 for some reason is not rendering it properly. :(

If you share your address or send an email to support @ 42crunch.com, we can send you the token manually split into sections.

**Comment by simonech** [comment]
I got it already thx, using gmail.
All good
