### ISSUE TITLE
extension icon not visible in left toolbar

### ISSUE THREAD

**Issue by chisholmd** [42Crunch/vscode-openapi#52]
I installed the extension, opened a yaml file and begane working.  At one point the icon disappeared from the left toolbar.  VSCode says that the extension is installed and enabled, but no matter what yaml file I open...no icon... How do I ...relaunch it?

I used teh instructions to create a openAPI3 file and the extenion activated again. so...  perhaps I managled my other file somehow.

**Comment by magic5644** [comment]
I confirm, same since last Visual Studio Code update 1.44

**Comment by ak1394** [comment]
Thanks for reporting! It looks like the extension has failed to initialise for some reason. Could you try checking Console in Developer tools (Help -> Toggle Developer Tools) to see if there is any error messages present?

**Comment by magic5644** [comment]
The problem is not thereanymore, since last update VS Code 1.45
