### ISSUE TITLE
Feature request: add ability to call endpoints defined in swagger

### ISSUE THREAD

**Issue by jackbravo** [42Crunch/vscode-openapi#55]
It would be great if the extension allowed calling the endpoints defined in the swagger, either directly in a custom interface. Or by simply launching and displaying the swagger output similar to https://editor.swagger.io/

**Comment by ak1394** [comment]
Thanks for suggestion! We'll look into adding it to the future versions.

**Comment by ak1394** [comment]
We've implemented SwaggerUI preview mode, which allows invoking operations from the UI.
