### ISSUE TITLE
Cannot Preview Anymore. 

### ISSUE THREAD

**Issue by Tawfeeqmeeri** [42Crunch/vscode-openapi#57]
I cannot preview my yaml file. It says 'cannot read 'c:\' 
I get this error when trying to perform security audit:
Failed to audit: Error: cannot open file:///c%3A/. Detail: Unable to read file 'c:\' (Error: Unable to read file 'c:\' that is actually a directory)

**Comment by ak1394** [comment]
What is your VS Code version? Could you provide full path to the file you're trying to audit?

**Comment by Tawfeeqmeeri** [comment]
It is the latest version, I've checked that. Also, I've deleted and reinstalled it just in case. 

C:\Users\Username\Documents\folder1\folder2\folder3\folder4\folder5\folder6\openapifolder

**Comment by ak1394** [comment]
Does it still happen with the latest version of the extension (3.2.0)? I tried, but couldn't reproduce your issue locally.

**Comment by ak1394** [comment]
Closing as an old issue. Please reopen if the problem still persists.
