### ISSUE TITLE
OpenAPI button disappears on save

### ISSUE THREAD

**Issue by aguarino77** [42Crunch/vscode-openapi#58]
If I create a new file using the "Create new openApi" the button appears on the left-hand panel.
As soon as I save the file to anything.json the button disappears, as if the plugin does not catch this is an openApi file any more.
And I cannot see the button for any valid swagger.json file.

Is there maybe an interference with other extensions?
Any ideas?

**Comment by ak1394** [comment]
Do you have the same issues if you try to create/edit files in YAML format?

What's the contents of "files.associations" in your settings.json?

**Comment by GauntletPL** [comment]
@aguarino77 please check what is the 'Language Mode' for the file that you're editing. For me it changed to 'JSON with comments' for some reason and that was what caused the button to disappear.

**Comment by aguarino77** [comment]
You are absolutely right! Thank you
