### ISSUE TITLE
API icon disappears on Color Theme change and zoom in/out

### ISSUE THREAD

**Issue by DSotnikov** [42Crunch/vscode-openapi#6]
Repro steps:
1. Open an OpenAPI file.
2. Observe that the left-hand pane gets the API icon.
3. Do one of the following:
- File / Preferences / Color Theme - and change the theme.
- View / Appearance / Zoom In
- View / Appearance / Zoom Out
4. Observe that the API icon is now gone.

Closing and re-opening the OpenAPI file returns the icon.

**Comment by ak1394** [comment]
Fixed in the upcoming 1.8.19 update.
