### ISSUE TITLE
Navigating to another document removes the "View detailed report for..." option

### ISSUE THREAD

**Issue by wegel** [42Crunch/vscode-openapi#60]
After running a Security Audit, if you navigate to another document and then come back to the OpenAPI document you audited, you lose the "View detailed report for..." option when hovering over problems on the OpenAPI document.

**Comment by ak1394** [comment]
By navigating to another document, do you mean something simple like switching to another tab or opening a new file? I tried to reproduce the issue, but I never seem to loose 'View detailed...'

Could you provide more steps to reproduce?

**Comment by ak1394** [comment]
Closing as an old issue. Please reopen if it still happens in the current version of the extension.
