### ISSUE TITLE
Completions support at $ref from other openapi spec files

### ISSUE THREAD

**Issue by gayanper** [42Crunch/vscode-openapi#66]
From where I come from, we use specs to define shared definitions/schemas and reference them in other specifications where a shared definition is used. The shared spec is a proper OpenAPI spec file which has a dummy path to confirms to the specification. I would like to get completion support for definitions inside the shared specs when they are referred as

$ref: "shared-spec.yml#$"

$ sign represents the caret position where auto completion is triggered. When triggered I would expect that will get the definitions/schemas from the shared-spec.yml file.

**Comment by ak1394** [comment]
Thanks for suggestion!  We have plans to improve completion support for external references, including suggestions for the filenames, but we haven't got around to implement it yet.

Your request is somewhat more limited in scope which makes it easier to implement, so I'll address it soon!

**Comment by gayanper** [comment]
I tried it locally and get it to working state. I will test more and make PR for you to validate soon.

**Comment by ak1394** [comment]
Thanks! PR is more than welcome!
