### ISSUE TITLE
PLugin wrongly picks this json file as an OAS file

### ISSUE THREAD

**Issue by pleothaud** [42Crunch/vscode-openapi#7]

**Comment by pleothaud** [comment]
[apipub.txt](https://github.com/42Crunch/vscode-openapi/files/3387407/apipub.txt)

**Comment by pleothaud** [comment]
Another file with the problem (this time assess v2 report, while first one was assess v3 report)

And BTW I had to rename the files from *.json to *.txt because it seems that Github is not accepting json files as atached files...

[JSONOutputAssessD.txt](https://github.com/42Crunch/vscode-openapi/files/3390915/JSONOutputAssessD.txt)

**Comment by ak1394** [comment]
Fixed in 1.8.6
