### ISSUE TITLE
API tab not showing with SSH FS

### ISSUE THREAD

**Issue by icabbi-joegarlick** [42Crunch/vscode-openapi#72]
Hello!

I am currently writing an API and developing it straight on to the server using an extension called [SSH FS](https://github.com/SchoofsKelvin/vscode-sshfs), It is really useful as it means you do not have to download any directories and they are retrieved on the fly. However when I open a OpenAPI file from SSH FS the side tab that opens the extension up never appears.

Is there a way to force the extension to open?

Thanks,
Joe

**Comment by ak1394** [comment]
Hi! Thanks for reporting the issue. I haven't tried SSH FS, I'll take a look and see what could be done about it.

**Comment by ak1394** [comment]
I've added support for SSH FS (and other filesystem providers). The change will be a part of the next release.
