### ISSUE TITLE
Support Open API 3.0.3

### ISSUE THREAD

**Issue by jbaron-mx** [42Crunch/vscode-openapi#73]
[OAS 3.0.3](https://github.com/OAI/OpenAPI-Specification/releases/tag/3.0.3) was released in February this year.

It looks like all features (IntelliSense, code nav, etc...) seem to work with the new version, except for the Security Audit, which always returns `No issues found in this file` no matter if there are obvious issues.

Is there any plan for the Security Audit to support the new version?

**Comment by ak1394** [comment]
Could you provide a sample of the file you're trying to audit?

**Comment by ak1394** [comment]
Thanks! The 3.0.3 is currently not supported (as you have reported). We intend to support it, but I don't have a specific dates for it yet. I'll update the ticket once I know more.

**Comment by ak1394** [comment]
Support for OpenAPI 3.0.3 has been added with the recent update.
