### ISSUE TITLE
Pin the OpenAPI button

### ISSUE THREAD

**Issue by Sparticuz** [42Crunch/vscode-openapi#78]
It would be nice and less jarring if the OpenAPI button would not disappear if I switch to another file. Maybe if the extension sees a `swagger.json` or `openapi.yml`, etc... file in the project it would not disappear.

EDIT: It would also allow me to quickly get back to my api design to make any changes or reference any paths

**Comment by ak1394** [comment]
Thanks for your feedback! I'll discuss it with the team, but for now I think it might be a reasonable approach to show OpenAPI button in the activity bar if user did open at least one OpenAPI file, and never hide it even if user switches away from the OpenAPI file.

What do you think?

**Comment by vfateev** [comment]
Fixed

**Comment by ak1394** [comment]
So, we've fixed the issue using the new 'viewsWelcome' API, and this will make it so the OpenAPI button is shown at all times, from the start even if there is no OpenAPI files open.

**Comment by lautriva** [comment]
Sorry to bring back the issue
I found your extension recently and I have a question regarding this issue

My use case: I use vscode for many different projects and a majority of them doesn't require OpenAPI (example: working on a video game)

Would it be possible to have a workspace setting to either globally show or hide the OpenApi button?

Another approach would be to only show the button if the current file opened is `openapi.yml` (or a file in a new user-defined setting where they put a list of files, something like `files.readonlyInclude` but for a whitelist of files defined as OpenAPI file)

**Comment by ak1394** [comment]
Hi @lautriva this is something best handled by VS Code itself. I think you can enable/disable extensions per workspace (click on a gear icon in the extensions and there would be something like `Disable (Workspace)`. Else, maybe using Profiles will be more convenient https://code.visualstudio.com/docs/editor/profiles
