### ISSUE TITLE
Swagger UI Try out not working

### ISSUE THREAD

**Issue by shavo007** [42Crunch/vscode-openapi#80]
Hi,

When I enable preview mode for swagger UI, i want to test out my API locally via Try it out.

But in vscode i get a console error:

```
[Embedded Page] Refused to connect to 'http://localhost:8080/documents' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.
```

Not sure if this is related to the extension?

**Comment by ak1394** [comment]
Hi! This is caused by the tight content security policy used by the extension. I'll see if I can relax it enough to make try it out to work.

**Comment by generalov** [comment]
https://github.com/42Crunch/vscode-openapi/blob/a0a7f2a02739a02c4e0f88118c4dea9317eb1d47/src/preview.ts#L150
I've added `connect-src: https:;` to the CSP directive and preview works fine for me.

**Comment by vfateev** [comment]
Fixed
