### ISSUE TITLE
Triggers errors on VS Code json files

### ISSUE THREAD

**Issue by segevfiner** [42Crunch/vscode-openapi#81]
VS Code uses a special dialect of JSON for it's configuration files that supports comments and trailing comma. This extension tries to parse such files triggering JSON parsing errors when they contain such elements. This extension should not generate such errors, maybe even ignoring such files in the first place.

To reproduce:
1. Open VS Code `settings.json`, and have a trailing comma in the top level JSON object. This is valid in VS Code, but this extension tries to parse it and raises errors about it.

**Comment by ak1394** [comment]
Thanks for reporting! Our extension should in fact support JSONC, so this behaviour is likely a bug.
