### ISSUE TITLE
Consider keyboard shortcut for "OpenAPI: show preview using the default renderer"

### ISSUE THREAD

**Issue by segevfiner** [42Crunch/vscode-openapi#83]
The other "Swagger Viewer" extension that does preview has a default keyboard shortcut for its preview command, consider also having a keyboard shortcut for the preview command of this extension for users migrating from it.

**Comment by ak1394** [comment]
Thanks for the suggestion, I'll include the shortcut in the next update.

**Comment by vfateev** [comment]
Fixed
