### ISSUE TITLE
Confusing error message on invalid OpenAPI files

### ISSUE THREAD

**Issue by DSotnikov** [42Crunch/vscode-openapi#84]
I tried doing a security audit on an OpenAPI file that had formatting issues and got this error message: "Failed to audit: Error: Failed to parse JSON: InvalidSymbol at offset 9168, CommaExpected at offset 9173, ColonExpected at offset 19875"

It would have been much nicer if instead it would give me the line numbers. It actually does put the issues in the Problems panel - which is very helpful, but took me time to find that out. Maybe you could update the text in the error message to mention that.

**Comment by vfateev** [comment]
Security audit and preview icons are now disabled if selected openapi file contains errors (formatting issues).
(The same behavior as in Idea and Eclipse plugins).
