### ISSUE TITLE
Identify bad or invalid $ref's with a warning

### ISSUE THREAD

**Issue by jc43081** [42Crunch/vscode-openapi#86]
When a $ref does not resolve either within the document or to an external model, the OAS becomes invalid. If the Preview is not open and you try to open it with a bad reference, it will warn you of the problem and tell you which reference is invalid. 

If the Preview is already open, the Preview will stop updating until the bad reference is resolved. No warning or indication is given to the problem. 

Enhancement Request.
Add a visual warning to the bad reference and add it to the Problems view.

**Comment by ak1394** [comment]
Thanks for the report! We plan to do better error reporting for broken $refs, likely in the next release or one after that.

**Comment by ak1394** [comment]
Fixed in the upcoming 3.10.0. For now the invalid refs will be shown only in audit or preview mode, but in the future version we will be showing invalid refs in the normal editing mode as well.
