### ISSUE TITLE
"Try it out" not working

### ISSUE THREAD

**Issue by mstimvol** [42Crunch/vscode-openapi#88]
I've very simple oas yml:

```
openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: http://localhost:8080
paths:
  /:
    get:
      responses:
        '200':
          description: OK
```

My webserver (fastify) is listening on port 8080 with enabled logger. When I open the preview, click on "Try it out" and execute the route, it tells me `curl -X GET "http://localhost:8080/" -H  "accept: */*"` But nothing has been executed... fastify never logs anything. But when I execute the command directly in the CLI, fastify responds correctly. So is the "Try it out"-feature currently broken or am I doing something wrong?

**Comment by ak1394** [comment]
Yes, this is the same issue as https://github.com/42Crunch/vscode-openapi/issues/80 we'll address it in the future releases.
