### ISSUE TITLE
Consider publishing to open-vsx

### ISSUE THREAD

**Issue by 1000101** [42Crunch/vscode-openapi#98]
The libre distribution of VS Code (VS Codium) is now by default configured to use https://open-vsx.org/ instead of the Microsoft Marketplace for licensing reasons.

https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace

Please consider publishing the extension there.
Wiki Guide https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

Thanks!

**Comment by tdemin** [comment]
Arch Linux distribution of Code-OSS also uses that. Basically, only users of the binary distribution of Visual Studio Code can ever use the MS extensions marketplace.

**Comment by ak1394** [comment]
We will publish the next version of the plugin to openvsx. The current version of the plugin is published by open-vsx, but the next one will be published by us.

**Comment by ak1394** [comment]
Published 4.0.2 to OpenVSX
