### ISSUE TITLE
swagger ui "try it out" problem again

### ISSUE THREAD

**Issue by blatoo** [42Crunch/vscode-openapi#99]
I can not use "preview mode" in vscode the "try it out" function:

I simply want run: http://localhost:9000/todos , but it always return: **TypeError: Failed to fetch**, however, when I use my webbrowser, it works totally fine. 

Here is my `swagger.yml` file: 
```
openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: 'http://localhost:9000'
paths:
  /todos:
    get:
      responses:
        '200':
          description: OK!
```

Actually I saw the same question in a  previous thread, but @vfateev said it was solved: 
https://github.com/42Crunch/vscode-openapi/issues/80

But, it doesn't looks like solved in version 3.8.0 ....

**Comment by ak1394** [comment]
Could you try opening developer tools panel as described here https://code.visualstudio.com/api/extension-guides/webview#inspecting-and-debugging-webviews and inspecting the error messages on the console of the devtools? 

It would be helpful if you could provide more detailed error message then the one shown by Swagger UI

**Comment by blatoo** [comment]
@ak1394 Thanks very much for the help. The problem disappeared, after I open the devtool. I have no idea, why this happens, but I guess, may be cache...

**Comment by ak1394** [comment]
@blatoo Happy to hear! :)
